import React, { useState } from 'react';
import { 
  X, Zap, CheckCircle2, Copy, Check, Terminal, Cpu, Layers, Code, 
  Server, ShieldCheck, Sparkles, ExternalLink, RefreshCw, Smartphone, Play
} from 'lucide-react';
import confetti from 'canvas-confetti';

const AI_PLATFORMS = [
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    badge: 'AGY SDK',
    icon: Zap,
    color: 'from-cyan-500 to-blue-600',
    border: 'border-cyan-500/40',
    textColor: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    configFile: '~/.gemini/antigravity/rules',
    description: 'Connexion directe avec l\'environnement Google Antigravity 2.0, les sous-agents autonomes et les slash commands natives.',
    features: [
      'Orchestration multi-agents (/teamwork-preview)',
      'Objectifs persistants autonomes (/goal)',
      'Intégration directe BigQuery, Firebase & Flutter SDK',
      'Exécution asynchrone non-bloquante (/schedule)'
    ],
    generateConfig: (stack) => `# Google Antigravity Rules Configuration
# Generated by KortexDeck (Cohen Web Studio)
# Target: ~/.gemini/antigravity/rules/kortexdeck.rule

[KORTEXDECK_AI_STACK]
Platform: Google Antigravity
Total Skills Active: ${stack.length}

${stack.map((item, i) => `## Skill ${i + 1}: ${item.title}
Command: ${item.command}
Type: ${item.type}
Directive: ${item.description}
Example: ${item.example}`).join('\n\n')}`
  },
  {
    id: 'claude',
    name: 'Anthropic Claude',
    badge: 'Claude Code & Desktop',
    icon: Cpu,
    color: 'from-amber-500 to-orange-600',
    border: 'border-amber-500/40',
    textColor: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    configFile: '~/.claude/CLAUDE.md',
    description: 'Passerelle dédiée pour Claude Code CLI, Claude 3.7 Sonnet thinking mode et Claude Desktop avec MCP.',
    features: [
      'Support intégral des balises XML structurelles',
      'Optimisation du cache de contexte (-90% de coût)',
      'Inspection et revue de Pull Requests (/review, /pr_comments)',
      'Déclencheur de pensée étendue <thinking>'
    ],
    generateConfig: (stack) => `# CLAUDE.md - Directives de projet KortexDeck
# Généré pour Claude Code CLI & Claude Desktop (Anthropic)
# Synchronisation: https://cohenwebstudio.com/kortexdeck

## Directives d'Exécution & Outils Recommandés (${stack.length} éléments)

${stack.map((item, i) => `### ${i + 1}. ${item.title}
- **Commande** : \`${item.command}\`
- **Rôle** : ${item.summary}
- **Syntaxe** : \`${item.syntax || item.command}\`
- **Pattern de prompt** : ${item.example}`).join('\n\n')}`
  },
  {
    id: 'cursor',
    name: 'Cursor IDE',
    badge: 'Cursor Composer',
    icon: Code,
    color: 'from-emerald-500 to-teal-600',
    border: 'border-emerald-500/40',
    textColor: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    configFile: '~/.cursorrules',
    description: 'Injection directe de directives intelligentes pour Cursor Composer, l\'indexation vectorielle @codebase et le linter IA.',
    features: [
      'Directives strictes TypeScript & Clean Architecture',
      'Indexation de codebase sémantique (@codebase)',
      'Contrôle automatique de l\'accessibilité A11y & ARIA',
      'Génération de tests unitaires TDD avant code'
    ],
    generateConfig: (stack) => `# .cursorrules - KortexDeck Rule Set
# Place in ~/.cursorrules or project root .cursorrules
# Powered by Cohen Web Studio

# 1. CORE ARCHITECTURAL INVARIANTS
- Strictly avoid 'any' in TypeScript; leverage Zod inference and explicit interfaces.
- Verify OWASP security standards and enforce PostgreSQL Row Level Security (RLS).
- Prioritize modular components with zero redundant side-effects.

# 2. ACTIVE COMMANDS & TOOLS INJECTED (${stack.length} ITEMS)
${stack.map((item) => `## [${item.platform.toUpperCase()}] ${item.title}
# Command: ${item.command}
# Rule: ${item.description}
# Example prompt: ${item.example}`).join('\n\n')}`
  },
  {
    id: 'codex',
    name: 'OpenAI Codex & Copilot',
    badge: 'Codex / GPT-4o / Copilot',
    icon: Layers,
    color: 'from-purple-500 to-indigo-600',
    border: 'border-purple-500/40',
    textColor: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    configFile: 'system_prompt.json',
    description: 'Générateur de System Prompts hautement structurés pour OpenAI Codex, GitHub Copilot CLI et APIs GPT-4o.',
    features: [
      'Génération de commandes shell complexes (gh copilot suggest)',
      'Refactorings algorithmiques et migration de frameworks',
      'JSON Schema enforcement & format de sortie Pydantic',
      'Conversion et traduction multi-langages'
    ],
    generateConfig: (stack) => JSON.stringify({
      system_instructions: {
        role: "Principal AI Engineer & Code Architect",
        engine: "OpenAI Codex / GPT-4o Engine",
        orchestrator: "KortexDeck (Cohen Web Studio)",
        active_tools_count: stack.length,
        commands_registry: stack.map(it => ({
          command: it.command,
          name: it.title,
          category: it.category,
          syntax: it.syntax || it.command,
          example: it.example
        }))
      }
    }, null, 2)
  }
];

export default function AIBridgeModal({ isOpen, onClose, favoriteItems }) {
  const [selectedPlatform, setSelectedPlatform] = useState('antigravity');
  const [copied, setCopied] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [syncResult, setSyncResult] = useState(null);

  if (!isOpen) return null;

  const currentPlat = AI_PLATFORMS.find(p => p.id === selectedPlatform) || AI_PLATFORMS[0];
  const activeStack = favoriteItems && favoriteItems.length > 0 ? favoriteItems : [];
  const generatedCode = currentPlat.generateConfig(activeStack);

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    try {
      confetti({ particleCount: 30, spread: 50, origin: { y: 0.6 } });
    } catch (_) {}
    setTimeout(() => setCopied(false), 2000);
  };

  const handleLiveSync = async () => {
    setSyncing(true);
    setSyncResult(null);

    try {
      const res = await fetch('/api/sync-local', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ items: activeStack })
      });
      const data = await res.json();
      if (res.ok && data.success) {
        setSyncResult({ success: true, message: `Connecté et synchronisé avec succès vers ${currentPlat.name} !` });
        try { confetti({ particleCount: 50, spread: 70 }); } catch (_) {}
      } else {
        throw new Error(data.error || 'Erreur de synchronisation.');
      }
    } catch (err) {
      setSyncResult({ success: false, message: `Copiez la configuration ci-dessous dans votre fichier ${currentPlat.configFile}` });
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md animate-fadeIn">
      <div 
        className="relative w-full max-w-4xl bg-slate-900 border border-slate-700/80 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex items-center justify-between bg-slate-950/70">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-gradient-to-br from-cyan-500 via-indigo-500 to-amber-500 text-slate-950 shadow-lg shadow-cyan-500/20">
              <Server className="w-6 h-6 font-bold" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-bold text-white">Passerelle & Connexion IA Multi-Plateforme</h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-300 border border-cyan-500/30">
                  Zero-API Required
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Connectez instantanément votre stack d'outils à Claude, Antigravity, Codex & Cursor
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Platform Selector Tabs */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 p-4 bg-slate-950/50 border-b border-slate-800">
          {AI_PLATFORMS.map((plat) => {
            const IconCmp = plat.icon;
            const isSelected = selectedPlatform === plat.id;

            return (
              <button
                key={plat.id}
                onClick={() => {
                  setSelectedPlatform(plat.id);
                  setSyncResult(null);
                }}
                className={`flex items-center gap-2.5 p-3 rounded-2xl border transition-all text-left ${
                  isSelected
                    ? `bg-slate-800/90 ${plat.border} shadow-lg shadow-cyan-500/10 scale-[1.02]`
                    : 'bg-slate-900/60 border-slate-800 hover:bg-slate-800/50 hover:border-slate-700'
                }`}
              >
                <div className={`p-2 rounded-xl bg-slate-900 border border-slate-800 ${plat.textColor}`}>
                  <IconCmp className="w-4 h-4" />
                </div>
                <div className="overflow-hidden">
                  <h4 className="text-xs font-bold text-white truncate">{plat.name}</h4>
                  <span className="text-[10px] font-mono text-slate-400 block truncate">{plat.badge}</span>
                </div>
              </button>
            );
          })}
        </div>

        {/* Body Content */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 text-slate-200">
          {/* Platform Info Banner */}
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className={`text-xs font-mono font-bold px-2 py-0.5 rounded ${currentPlat.bgColor} ${currentPlat.textColor} border ${currentPlat.border}`}>
                  {currentPlat.name}
                </span>
                <span className="text-xs font-mono text-slate-400">
                  Fichier cible : <code className="text-amber-300">{currentPlat.configFile}</code>
                </span>
              </div>
              <p className="text-xs text-slate-300 leading-relaxed">
                {currentPlat.description}
              </p>
            </div>

            <button
              onClick={handleLiveSync}
              disabled={syncing}
              className="whitespace-nowrap px-4 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-amber-500 hover:from-cyan-400 hover:to-amber-400 text-slate-950 font-bold text-xs shadow-md shadow-cyan-500/20 transition-all flex items-center gap-1.5"
            >
              {syncing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4 fill-current" />}
              <span>⚡ Connecter & Injecter la Stack</span>
            </button>
          </div>

          {/* Sync Status Feedback */}
          {syncResult && (
            <div className={`p-3.5 rounded-xl text-xs flex items-center gap-2 border ${
              syncResult.success 
                ? 'bg-emerald-950/40 border-emerald-500/40 text-emerald-300' 
                : 'bg-amber-950/40 border-amber-500/40 text-amber-300'
            }`}>
              <CheckCircle2 className="w-4 h-4" />
              <span>{syncResult.message}</span>
            </div>
          )}

          {/* Key Features List */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            {currentPlat.features.map((feat, idx) => (
              <div key={idx} className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-950/40 border border-slate-800/80 text-xs">
                <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0" />
                <span className="text-slate-300">{feat}</span>
              </div>
            ))}
          </div>

          {/* Configuration Code Preview */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-cyan-400 flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5" />
                Configuration Générée ({activeStack.length} outils dans la stack) :
              </span>
              <button
                onClick={handleCopyCode}
                className={`flex items-center gap-1.5 px-3 py-1 rounded-lg text-xs font-mono font-semibold transition-all ${
                  copied
                    ? 'bg-emerald-500 text-slate-950 font-bold'
                    : 'bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700'
                }`}
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? "Copié !" : "Copier la configuration"}</span>
              </button>
            </div>

            <pre className="p-4 bg-slate-950 rounded-2xl border border-slate-800 text-xs font-mono text-cyan-300/90 overflow-x-auto max-h-56 select-all">
              {generatedCode}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between">
          <span className="text-[11px] text-slate-500 font-mono">
            KortexDeck Neural Bridge • Cohen Web Studio
          </span>
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-colors"
          >
            Fermer
          </button>
        </div>
      </div>
    </div>
  );
}
