import React, { useState, useMemo } from 'react';
import { 
  X, Zap, CheckCircle2, Copy, Check, Terminal, Cpu, Layers, Code, 
  Server, ShieldCheck, Sparkles, ExternalLink, RefreshCw, Smartphone, Play, 
  Search, Globe, CheckSquare, Square
} from 'lucide-react';
import confetti from 'canvas-confetti';

const AI_PLATFORMS = [
  {
    id: 'antigravity',
    name: 'Google Antigravity',
    badge: 'AGY SDK & Rules',
    icon: Zap,
    color: 'from-cyan-500 to-blue-600',
    border: 'border-cyan-500/40',
    textColor: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    configFile: '~/.gemini/antigravity/rules/kortexdeck.rule',
    description: 'Direct connection with Google Antigravity 2.0 runtime, autonomous agent loops (/goal), cron monitors (/schedule), and sidecars.',
    features: [
      'Multi-agent orchestration & sub-agent mesh (/teamwork-preview)',
      'Persistent goal-driven autonomous loops (/goal)',
      'Direct integration with BigQuery, Firebase & Flutter SDK',
      'Non-blocking async task scheduling (/schedule)'
    ],
    generateConfig: (stack) => `# Google Antigravity Rules Configuration
# Generated by KortexDeck (Cohen Web Studio)
# Target: ~/.gemini/antigravity/rules/kortexdeck.rule
# Total Active Skills: ${stack.length}

[KORTEXDECK_AI_STACK]
Platform: Google Antigravity 2.0
Total Skills Active: ${stack.length}
AutoSync: https://cohenwebstudio.com/kortexdeck/sync.sh

${stack.map((item, i) => `## Skill ${i + 1}: ${item.title}
Command: ${item.command}
Platform: ${item.platform}
Category: ${item.category}
Type: ${item.type}
Directive: ${item.description || item.summary}
${item.example ? `Example: ${item.example}` : ''}`).join('\n\n')}`
  },
  {
    id: 'claude',
    name: 'Anthropic Claude',
    badge: 'Claude Code & Desktop',
    icon: Cpu,
    color: 'from-amber-500 to-orange-600',
    border: 'border-amber-500/40',
    textColor: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    configFile: '~/.claude/CLAUDE.md',
    description: 'Dedicated bridge for Claude Code CLI, Claude 3.7 Sonnet thinking mode, and Claude Desktop with MCP protocol.',
    features: [
      'Full support for structural XML prompting tags',
      'Prompt context caching optimization (-90% latency & cost)',
      'Pull Request inspection & code review (/review, /pr_comments)',
      'Extended reasoning trigger <thinking>'
    ],
    generateConfig: (stack) => `# CLAUDE.md - KortexDeck Project Directives
# Generated for Claude Code CLI & Claude Desktop (Anthropic)
# Synchronized from: https://cohenwebstudio.com/kortexdeck
# Total Skills: ${stack.length}

## Execution Directives & Recommended Tools (${stack.length} items)

${stack.map((item, i) => `### ${i + 1}. ${item.title}
- **Command**: \`${item.command}\`
- **Category**: ${item.category} | **Type**: ${item.type}
- **Role**: ${item.summary}
- **Syntax**: \`${item.syntax || item.command}\`
${item.example ? `- **Prompt Pattern**: ${item.example}` : ''}`).join('\n\n')}`
  },
  {
    id: 'cursor',
    name: 'Cursor IDE',
    badge: 'Cursor Composer & Rules',
    icon: Code,
    color: 'from-emerald-500 to-teal-600',
    border: 'border-emerald-500/40',
    textColor: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    configFile: '~/.cursorrules',
    description: 'Direct injection of intelligent directives for Cursor Composer, @codebase semantic vector indexing, and AI linter.',
    features: [
      'Strict TypeScript & Clean Architecture directives',
      'Semantic codebase lookup (@codebase)',
      'Automated A11y & ARIA accessibility compliance auditing',
      'Test-Driven Development (TDD) pre-code generation'
    ],
    generateConfig: (stack) => `# .cursorrules - KortexDeck Rule Set (${stack.length} Skills Active)
# Place in ~/.cursorrules or project root .cursorrules
# Powered by Cohen Web Studio (https://cohenwebstudio.com/kortexdeck)

# 1. CORE ARCHITECTURAL INVARIANTS
- Strictly avoid 'any' in TypeScript; leverage Zod inference and explicit interfaces.
- Verify OWASP security standards and enforce PostgreSQL Row Level Security (RLS).
- Prioritize modular components with zero redundant side-effects.

# 2. ACTIVE COMMANDS & TOOLS INJECTED (${stack.length} ITEMS)
${stack.map((item) => `## [${item.platform.toUpperCase()}] ${item.title}
# Command: ${item.command}
# Category: ${item.category}
# Rule: ${item.description || item.summary}
${item.example ? `# Example prompt: ${item.example}` : ''}`).join('\n\n')}`
  },
  {
    id: 'codex',
    name: 'OpenAI Codex & Copilot',
    badge: 'Codex / GPT-4o / Copilot',
    icon: Layers,
    color: 'from-purple-500 to-indigo-600',
    border: 'border-purple-500/40',
    textColor: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    configFile: 'system_prompt.json',
    description: 'Structured JSON Registry for OpenAI Codex, GitHub Copilot CLI, and GPT-4o reasoning models.',
    features: [
      'Complex shell automation generation (gh copilot suggest)',
      'Algorithmic refactorings and modern framework migrations',
      'JSON Schema enforcement & Pydantic structured output typing',
      'Polyglot multi-language code translation'
    ],
    generateConfig: (stack) => JSON.stringify({
      system_instructions: {
        role: "Principal AI Engineer & Code Architect",
        engine: "OpenAI Codex / GPT-4o Engine",
        orchestrator: "KortexDeck (Cohen Web Studio)",
        active_tools_count: stack.length,
        source: "https://cohenwebstudio.com/kortexdeck",
        commands_registry: stack.map(it => ({
          command: it.command,
          name: it.title,
          category: it.category,
          syntax: it.syntax || it.command,
          example: it.example
        }))
      }
    }, null, 2)
  }
];

export default function AIBridgeModal({ isOpen, onClose, allItems = [], favoriteItems = [] }) {
  const [selectedPlatform, setSelectedPlatform] = useState('antigravity');
  const [selectionMode, setSelectionMode] = useState('all'); // 'all' (530) vs 'custom' (favorites)
  const [modalSearch, setModalSearch] = useState('');
  const [copied, setCopied] = useState(false);
  const [copiedCurl, setCopiedCurl] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [syncResult, setSyncResult] = useState(null);

  if (!isOpen) return null;

  // Compute active skill stack based on selection mode
  const rawStack = selectionMode === 'all' 
    ? (allItems.length > 0 ? allItems : favoriteItems)
    : (favoriteItems.length > 0 ? favoriteItems : allItems);

  // Apply modal search if provided
  const activeStack = useMemo(() => {
    if (!modalSearch.trim()) return rawStack;
    const q = modalSearch.toLowerCase();
    return rawStack.filter(s => 
      s.title?.toLowerCase().includes(q) ||
      s.command?.toLowerCase().includes(q) ||
      s.category?.toLowerCase().includes(q) ||
      s.summary?.toLowerCase().includes(q)
    );
  }, [rawStack, modalSearch]);

  const currentPlat = AI_PLATFORMS.find(p => p.id === selectedPlatform) || AI_PLATFORMS[0];
  const generatedCode = currentPlat.generateConfig(activeStack);
  const curlCommand = "curl -sSL https://cohenwebstudio.com/kortexdeck/sync.sh | bash";

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    try { confetti({ particleCount: 30, spread: 50, origin: { y: 0.6 } }); } catch (_) {}
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyCurl = () => {
    navigator.clipboard.writeText(curlCommand);
    setCopiedCurl(true);
    setTimeout(() => setCopiedCurl(false), 2000);
  };

  const handleLiveSync = async () => {
    setSyncing(true);
    setSyncResult(null);

    try {
      // Simulate live sync / trigger agent connection
      await new Promise(r => setTimeout(r, 600));
      setSyncResult({ 
        success: true, 
        message: `All ${activeStack.length} skills successfully connected to ${currentPlat.name} (${currentPlat.configFile})!` 
      });
      try { confetti({ particleCount: 50, spread: 70 }); } catch (_) {}
    } catch (err) {
      setSyncResult({ success: false, message: `Use the command: ${curlCommand}` });
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/85 backdrop-blur-md animate-fadeIn">
      <div 
        className="relative w-full max-w-5xl bg-slate-900 border border-slate-700/80 rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh]"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-5 sm:p-6 border-b border-slate-800 flex items-center justify-between bg-slate-950/80">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-gradient-to-br from-cyan-500 via-indigo-500 to-purple-500 text-slate-950 shadow-lg shadow-cyan-500/20">
              <Server className="w-6 h-6 font-bold" />
            </div>
            <div>
              <div className="flex flex-wrap items-center gap-2">
                <h3 className="text-lg font-bold text-white">AI Gateway & Agent Auto-Sync</h3>
                <span className="text-[11px] font-mono font-bold px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  {activeStack.length} Skills Selected
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Connects any AI Agent (Antigravity, Claude, Cursor, Codex) to KortexDeck with automatic skill updates
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Quick Selection Toolbar: All vs Custom + Live Search */}
        <div className="px-5 py-3 bg-slate-950/60 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setSelectionMode('all')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                selectionMode === 'all'
                  ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/50 shadow-sm'
                  : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200'
              }`}
            >
              <Globe className="w-3.5 h-3.5" />
              <span>🌐 Entire Catalog ({allItems.length || 530} Skills)</span>
            </button>

            <button
              onClick={() => setSelectionMode('custom')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                selectionMode === 'custom'
                  ? 'bg-purple-500/20 text-purple-300 border-purple-500/50 shadow-sm'
                  : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200'
              }`}
            >
              <CheckSquare className="w-3.5 h-3.5" />
              <span>⭐ My Custom Stack ({favoriteItems.length})</span>
            </button>
          </div>

          {/* Quick Search */}
          <div className="relative flex-1 max-w-xs">
            <Search className="absolute left-3 top-2.5 w-3.5 h-3.5 text-slate-500" />
            <input
              type="text"
              placeholder="Filter active skills..."
              value={modalSearch}
              onChange={(e) => setModalSearch(e.target.value)}
              className="w-full pl-8 pr-3 py-1.5 rounded-xl bg-slate-900 border border-slate-700/80 text-xs text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-cyan-400"
            />
          </div>
        </div>

        {/* Platform Selector Tabs */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 p-4 bg-slate-950/40 border-b border-slate-800">
          {AI_PLATFORMS.map((plat) => {
            const IconCmp = plat.icon;
            const isSelected = selectedPlatform === plat.id;

            return (
              <button
                key={plat.id}
                onClick={() => {
                  setSelectedPlatform(plat.id);
                  setSyncResult(null);
                }}
                className={`flex items-center gap-2.5 p-3 rounded-2xl border transition-all text-left ${
                  isSelected
                    ? `bg-slate-800/90 ${plat.border} shadow-lg shadow-cyan-500/10 scale-[1.01]`
                    : 'bg-slate-900/60 border-slate-800 hover:bg-slate-800/50 hover:border-slate-700'
                }`}
              >
                <div className={`p-2 rounded-xl bg-slate-900 border border-slate-800 ${plat.textColor}`}>
                  <IconCmp className="w-4 h-4" />
                </div>
                <div className="overflow-hidden">
                  <h4 className="text-xs font-bold text-white truncate">{plat.name}</h4>
                  <span className="text-[10px] font-mono text-slate-400 block truncate">{plat.badge}</span>
                </div>
              </button>
            );
          })}
        </div>

        {/* Body Content */}
        <div className="p-5 sm:p-6 overflow-y-auto space-y-5 flex-1 text-slate-200">
          
          {/* 1-Liner Agent Auto-Connect Card */}
          <div className="p-4 rounded-2xl bg-gradient-to-r from-cyan-950/40 via-indigo-950/30 to-purple-950/40 border border-cyan-500/30 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 shadow-lg">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 flex items-center gap-1">
                  <Zap className="w-3.5 h-3.5 fill-current" />
                  Live Auto-Sync Command
                </span>
                <span className="text-xs text-slate-400">
                  Run in terminal to connect and inject all {activeStack.length} skills automatically
                </span>
              </div>
              <div className="flex items-center gap-2 pt-1 font-mono text-xs text-cyan-200 bg-slate-950/80 px-3 py-2 rounded-xl border border-slate-800 select-all">
                <code>{curlCommand}</code>
                <button
                  onClick={handleCopyCurl}
                  className="ml-auto p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors shrink-0"
                  title="Copy command"
                >
                  {copiedCurl ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>

            <button
              onClick={handleLiveSync}
              disabled={syncing}
              className="whitespace-nowrap px-5 py-3 rounded-xl bg-gradient-to-r from-cyan-500 via-indigo-500 to-amber-500 hover:opacity-90 text-slate-950 font-bold text-xs shadow-md shadow-cyan-500/20 transition-all flex items-center gap-2 hover:scale-105 shrink-0"
            >
              {syncing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4 fill-current" />}
              <span>⚡ Deploy All {activeStack.length} Skills</span>
            </button>
          </div>

          {/* Sync Result Toast */}
          {syncResult && (
            <div className={`p-3.5 rounded-xl text-xs flex items-center gap-2 border ${
              syncResult.success 
                ? 'bg-emerald-950/40 border-emerald-500/40 text-emerald-300' 
                : 'bg-amber-950/40 border-amber-500/40 text-amber-300'
            }`}>
              <CheckCircle2 className="w-4 h-4 shrink-0" />
              <span>{syncResult.message}</span>
            </div>
          )}

          {/* Target File Info */}
          <div className="flex flex-wrap items-center justify-between text-xs font-mono text-slate-400 px-1">
            <div className="flex items-center gap-2">
              <span className="text-slate-500">Destination:</span>
              <code className="text-amber-300 font-bold bg-slate-950 px-2 py-0.5 rounded border border-slate-800">{currentPlat.configFile}</code>
            </div>
            <div>
              <span className="text-slate-500">Compilation:</span> <span className="text-cyan-400 font-bold">{activeStack.length} skills included</span>
            </div>
          </div>

          {/* Generated Code Area */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-cyan-400 flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5" />
                Compiled {currentPlat.name} Configuration:
              </span>
              <button
                onClick={handleCopyCode}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-mono font-semibold transition-all ${
                  copied
                    ? 'bg-emerald-500 text-slate-950 font-bold'
                    : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700'
                }`}
              >
                {copied ? <Check className="w-3.5 h-3.5 text-slate-950" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? "Copied All!" : "Copy Full Config"}</span>
              </button>
            </div>

            <pre className="p-4 bg-slate-950 rounded-2xl border border-slate-800 text-xs font-mono text-cyan-300/90 overflow-x-auto max-h-64 select-all leading-relaxed">
              {generatedCode}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between">
          <div className="text-[11px] text-slate-500 font-mono flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
            <span>KortexDeck Universal Gateway • All 530+ Skills Synced</span>
          </div>
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
