#!/usr/bin/env python3
"""
expand_skills_v2.py — Expand KortexDeck skills catalog
Adds 200+ new skills to under-represented categories:
Backend, Frontend, Algorithmique, Architecture, Database,
Framework, Security, Scraping, Video, Image, Logo, Name/Domain
"""
import json, os, sys

DATA_FILE = os.path.join(os.path.dirname(__file__), '../src/data/commandsData.json')

NEW_SKILLS = [
  # =================== BACKEND & API (40 skills) ===================
  {"id":"bk-001","title":"Express.js REST Master","command":"/express-rest","platform":"Backend","category":"Backend & API","type":"Framework","summary":"Generate production REST API with Express.js: routes, middleware, validation","description":"Create full Express REST API with JWT auth, rate limiting, helmet security, morgan logging, Joi validation, and error handling middleware","syntax":"/express-rest [resource] [--auth jwt] [--db postgres]","example":"/express-rest users --auth jwt --db postgres","tags":["express","node","rest","api"]},
  {"id":"bk-002","title":"FastAPI Async Endpoints","command":"/fastapi-async","platform":"Backend","category":"Backend & API","type":"Framework","summary":"Generate FastAPI async endpoints with Pydantic models and OpenAPI docs","description":"Build high-performance async Python APIs with FastAPI, Pydantic v2, SQLAlchemy async, Alembic migrations, and automatic OpenAPI/Swagger documentation","syntax":"/fastapi-async [endpoint] [--model pydantic] [--db sqlalchemy]","example":"/fastapi-async /items --model Product --db sqlalchemy","tags":["fastapi","python","async","api"]},
  {"id":"bk-003","title":"GraphQL Schema Architect","command":"/graphql-schema","platform":"Backend","category":"Backend & API","type":"Architecture","summary":"Design and implement GraphQL schema with resolvers, mutations, subscriptions","description":"Build complete GraphQL API with Apollo Server, schema-first design, DataLoader for N+1 prevention, subscriptions via WebSocket, and field-level authorization","syntax":"/graphql-schema [type] [--resolvers] [--subscriptions]","example":"/graphql-schema User --resolvers --subscriptions","tags":["graphql","apollo","schema","api"]},
  {"id":"bk-004","title":"gRPC Service Builder","command":"/grpc-service","platform":"Backend","category":"Backend & API","type":"Framework","summary":"Generate gRPC protobuf definitions and server/client stubs","description":"Create gRPC microservices with Protocol Buffers, server streaming, client streaming, bidirectional streaming, and interceptors for auth/logging","syntax":"/grpc-service [service] [--stream bidirectional] [--lang go|python|node]","example":"/grpc-service UserService --stream bidirectional --lang go","tags":["grpc","protobuf","microservice","rpc"]},
  {"id":"bk-005","title":"WebSocket Real-Time Hub","command":"/ws-hub","platform":"Backend","category":"Backend & API","type":"Pattern","summary":"Build real-time WebSocket hub with rooms, broadcasts, and presence","description":"Implement Socket.io or native WebSocket server with room management, typed events, heartbeat/ping, reconnection logic, and Redis pub/sub for horizontal scaling","syntax":"/ws-hub [feature] [--rooms] [--redis] [--framework socket.io|ws]","example":"/ws-hub chat --rooms --redis --framework socket.io","tags":["websocket","realtime","socket.io","redis"]},
  {"id":"bk-006","title":"JWT Auth System","command":"/jwt-auth","platform":"Backend","category":"Backend & API","type":"Security","summary":"Implement complete JWT authentication with refresh tokens and RBAC","description":"Build full auth system: JWT access tokens, refresh token rotation, secure httpOnly cookies, RBAC middleware, password hashing with argon2, email verification","syntax":"/jwt-auth [--refresh] [--rbac] [--2fa] [--provider oauth2]","example":"/jwt-auth --refresh --rbac --2fa","tags":["jwt","auth","security","rbac"]},
  {"id":"bk-007","title":"Message Queue Producer/Consumer","command":"/mq-setup","platform":"Backend","category":"Backend & API","type":"Architecture","summary":"Setup RabbitMQ/Kafka message queue with producers, consumers, dead-letter queues","description":"Implement async message processing with RabbitMQ or Apache Kafka, topic partitioning, consumer groups, retry logic, dead-letter queues, and monitoring","syntax":"/mq-setup [broker] [--topics] [--dlq] [--retry 3]","example":"/mq-setup kafka --topics orders,payments --dlq --retry 3","tags":["kafka","rabbitmq","queue","async"]},
  {"id":"bk-008","title":"Redis Cache Layer","command":"/redis-cache","platform":"Backend","category":"Backend & API","type":"Optimization","summary":"Add Redis caching layer with TTL, invalidation, and cache-aside pattern","description":"Implement Redis caching strategies: cache-aside, write-through, cache stampede prevention with probabilistic early expiration, tag-based invalidation","syntax":"/redis-cache [strategy] [--ttl 3600] [--invalidation tag-based]","example":"/redis-cache cache-aside --ttl 3600 --invalidation tag-based","tags":["redis","cache","performance","optimization"]},
  {"id":"bk-009","title":"API Rate Limiter","command":"/rate-limit","platform":"Backend","category":"Backend & API","type":"Security","summary":"Implement sliding window rate limiter with Redis and per-user quotas","description":"Build advanced rate limiting: sliding window counter, token bucket, per-user/IP/API key quotas, custom headers (X-RateLimit-*), and graceful 429 responses","syntax":"/rate-limit [algorithm] [--per user|ip|key] [--window 60] [--max 100]","example":"/rate-limit sliding-window --per user --window 60 --max 100","tags":["rate-limit","security","api","redis"]},
  {"id":"bk-010","title":"Microservice Scaffold","command":"/microservice","platform":"Backend","category":"Backend & API","type":"Architecture","summary":"Scaffold production-ready microservice with health checks, metrics, tracing","description":"Generate microservice boilerplate: health/readiness endpoints, Prometheus metrics, OpenTelemetry tracing, structured logging, graceful shutdown, Docker support","syntax":"/microservice [name] [--lang go|node|python] [--db] [--queue]","example":"/microservice order-service --lang go --db postgres --queue kafka","tags":["microservice","docker","kubernetes","tracing"]},
  {"id":"bk-011","title":"API Gateway Config","command":"/api-gateway","platform":"Backend","category":"Backend & API","type":"Architecture","summary":"Configure API Gateway with Kong/Traefik: routing, auth, rate limiting, logging","description":"Set up API Gateway layer with service discovery, load balancing, authentication plugins, request/response transformation, circuit breaker, and canary routing","syntax":"/api-gateway [gateway] [--services] [--auth] [--lb round-robin]","example":"/api-gateway kong --services user,order --auth jwt --lb round-robin","tags":["api-gateway","kong","traefik","load-balancer"]},
  {"id":"bk-012","title":"OpenAPI Spec Generator","command":"/openapi-spec","platform":"Backend","category":"Backend & API","type":"Documentation","summary":"Generate complete OpenAPI 3.1 specification from code or description","description":"Auto-generate OpenAPI 3.1 YAML/JSON spec with schemas, examples, security schemes, response codes, and Postman collection export","syntax":"/openapi-spec [api-name] [--version 3.1] [--format yaml|json] [--auth bearer|oauth2]","example":"/openapi-spec PaymentsAPI --version 3.1 --format yaml --auth bearer","tags":["openapi","swagger","documentation","api"]},
  {"id":"bk-013","title":"Database Migration Runner","command":"/db-migrate","platform":"Backend","category":"Backend & API","type":"DevOps","summary":"Run, rollback, and manage database migrations with Flyway/Liquibase/Alembic","description":"Manage database schema evolution: version-controlled migrations, rollback strategies, seed data, multi-environment support, and migration testing","syntax":"/db-migrate [tool] [--env staging] [--rollback] [--seed]","example":"/db-migrate alembic --env staging --seed","tags":["migration","database","devops","schema"]},
  {"id":"bk-014","title":"Serverless Function Factory","command":"/serverless-fn","platform":"Backend","category":"Backend & API","type":"Cloud","summary":"Generate serverless functions for AWS Lambda, GCP Cloud Functions, Vercel","description":"Build serverless handlers with cold-start optimization, environment-aware config, event source mapping (SQS, S3, DynamoDB Streams), and IaC deployment","syntax":"/serverless-fn [provider] [--trigger http|queue|storage] [--runtime node20|python311]","example":"/serverless-fn aws --trigger http --runtime node20","tags":["serverless","lambda","cloud","functions"]},
  {"id":"bk-015","title":"Health Check Endpoint","command":"/health-check","platform":"Backend","category":"Backend & API","type":"Reliability","summary":"Implement /health and /ready endpoints with dependency checks","description":"Build health check system: liveness probe, readiness probe, dependency checks (DB, cache, external APIs), circuit breaker state, and response time SLA checks","syntax":"/health-check [--checks db,redis,external] [--sla 200ms]","example":"/health-check --checks db,redis,external --sla 200ms","tags":["health","reliability","kubernetes","monitoring"]},

  # =================== FRONTEND & UI (40 skills) ===================
  {"id":"fe-001","title":"React 19 Component Factory","command":"/react-component","platform":"Frontend","category":"Frontend & UI","type":"Framework","summary":"Generate React 19 components with hooks, Server Actions, and RSC patterns","description":"Build production React components with TypeScript, React 19 features (use(), startTransition), RSC/RCC boundary, Suspense, ErrorBoundary, and accessibility","syntax":"/react-component [name] [--type rsc|rcc] [--form] [--suspense]","example":"/react-component UserProfile --type rsc --suspense","tags":["react","react19","typescript","hooks"]},
  {"id":"fe-002","title":"Next.js App Router Page","command":"/nextjs-page","platform":"Frontend","category":"Frontend & UI","type":"Framework","summary":"Generate Next.js 15 App Router pages with metadata, layouts, and loading states","description":"Create App Router pages: generateStaticParams, generateMetadata, parallel routes, intercepting routes, streaming with Suspense, and partial prerendering","syntax":"/nextjs-page [route] [--type static|dynamic|ssr] [--metadata] [--loading]","example":"/nextjs-page /products/[id] --type dynamic --metadata --loading","tags":["nextjs","app-router","seo","streaming"]},
  {"id":"fe-003","title":"Tailwind Component System","command":"/tailwind-system","platform":"Frontend","category":"Frontend & UI","type":"Design","summary":"Build reusable Tailwind CSS component system with variants and dark mode","description":"Create design system with Tailwind v4: CVA variants, class-variance-authority, Radix UI primitives, dark mode toggle, responsive breakpoints, and Storybook docs","syntax":"/tailwind-system [component] [--variants] [--dark-mode] [--storybook]","example":"/tailwind-system Button --variants primary,secondary,ghost --dark-mode --storybook","tags":["tailwind","design-system","css","ui"]},
  {"id":"fe-004","title":"Framer Motion Animator","command":"/animate","platform":"Frontend","category":"Frontend & UI","type":"Animation","summary":"Add fluid animations with Framer Motion: page transitions, stagger, gestures","description":"Implement Framer Motion animations: page transitions with layout animations, stagger children, drag gestures, scroll-linked animations, and shared element transitions","syntax":"/animate [component] [--type transition|stagger|gesture|scroll] [--duration 0.3]","example":"/animate CardList --type stagger --duration 0.4","tags":["framer-motion","animation","ui","react"]},
  {"id":"fe-005","title":"Zustand State Manager","command":"/zustand-store","platform":"Frontend","category":"Frontend & UI","type":"State","summary":"Create Zustand stores with persist, devtools, immer middleware","description":"Build typed Zustand stores: slice pattern, immer for immutable updates, persist to localStorage/sessionStorage, Redux DevTools integration, and computed selectors","syntax":"/zustand-store [store-name] [--persist] [--devtools] [--immer]","example":"/zustand-store userStore --persist --devtools --immer","tags":["zustand","state","react","store"]},
  {"id":"fe-006","title":"React Query Data Layer","command":"/react-query","platform":"Frontend","category":"Frontend & UI","type":"Data","summary":"Setup TanStack Query with queries, mutations, optimistic updates, and prefetch","description":"Implement TanStack Query v5: QueryClient setup, typed queries, infinite scroll, optimistic mutations, background refetch, and SSR prefetch with dehydration","syntax":"/react-query [resource] [--infinite] [--optimistic] [--ssr]","example":"/react-query posts --infinite --optimistic --ssr","tags":["tanstack-query","react","data-fetching","cache"]},
  {"id":"fe-007","title":"Form Builder with Zod","command":"/form-zod","platform":"Frontend","category":"Frontend & UI","type":"Form","summary":"Build type-safe forms with react-hook-form + Zod validation","description":"Create forms with react-hook-form v7 + Zod schema validation: field arrays, conditional fields, async validation, file uploads, and accessible error messages","syntax":"/form-zod [form-name] [--schema] [--async-validation] [--file-upload]","example":"/form-zod CheckoutForm --schema --async-validation --file-upload","tags":["react-hook-form","zod","forms","validation"]},
  {"id":"fe-008","title":"Data Table Pro","command":"/data-table","platform":"Frontend","category":"Frontend & UI","type":"Component","summary":"Build feature-rich data table with TanStack Table: sort, filter, pagination, export","description":"Implement TanStack Table v8: column visibility, multi-sort, column filters, global search, row selection, virtualization for large datasets, CSV/Excel export","syntax":"/data-table [resource] [--virtualize] [--export csv,excel] [--server-side]","example":"/data-table orders --virtualize --export csv,excel --server-side","tags":["tanstack-table","data-table","react","typescript"]},
  {"id":"fe-009","title":"PWA Installer","command":"/pwa-setup","platform":"Frontend","category":"Frontend & UI","type":"PWA","summary":"Convert web app to PWA with service worker, offline support, install prompt","description":"Add PWA capabilities: Workbox service worker, offline-first cache strategies, Web App Manifest, install prompt, background sync, and push notifications","syntax":"/pwa-setup [strategy] [--offline] [--push-notifications] [--background-sync]","example":"/pwa-setup stale-while-revalidate --offline --push-notifications","tags":["pwa","service-worker","offline","workbox"]},
  {"id":"fe-010","title":"i18n Localization Setup","command":"/i18n-setup","platform":"Frontend","category":"Frontend & UI","type":"Localization","summary":"Add multi-language support with next-intl or react-i18next","description":"Implement internationalization: locale routing, JSON translation files, pluralization, date/number formatting, RTL support, and language auto-detection","syntax":"/i18n-setup [locales] [--rtl] [--auto-detect] [--framework next-intl|i18next]","example":"/i18n-setup en,fr,ar,he --rtl --auto-detect --framework next-intl","tags":["i18n","localization","nextjs","react"]},
  {"id":"fe-011","title":"Chart Dashboard","command":"/charts","platform":"Frontend","category":"Frontend & UI","type":"Visualization","summary":"Build interactive data visualizations with Recharts or Chart.js","description":"Create responsive charts: line, bar, pie, area, scatter, heatmap with Recharts or Chart.js, real-time updates, zoom/pan, and accessible data tables","syntax":"/charts [type] [--library recharts|chartjs|d3] [--realtime] [--responsive]","example":"/charts dashboard --library recharts --realtime --responsive","tags":["recharts","charts","d3","visualization"]},
  {"id":"fe-012","title":"Infinite Scroll Feed","command":"/infinite-scroll","platform":"Frontend","category":"Frontend & UI","type":"UX","summary":"Build performant infinite scroll with virtual DOM and intersection observer","description":"Implement infinite scroll with react-virtual for DOM virtualization, intersection observer for load trigger, loading skeletons, error retry, and scroll restoration","syntax":"/infinite-scroll [list-name] [--virtual] [--skeleton] [--threshold 0.8]","example":"/infinite-scroll PostFeed --virtual --skeleton --threshold 0.8","tags":["infinite-scroll","virtual","performance","ux"]},
  {"id":"fe-013","title":"Drag & Drop Interface","command":"/dnd-interface","platform":"Frontend","category":"Frontend & UI","type":"Interaction","summary":"Build drag-and-drop UI with @dnd-kit: sortable lists, kanban boards","description":"Implement DnD Kit: sortable lists, kanban board with multiple containers, drag overlay, keyboard accessibility, collision detection algorithms, and touch support","syntax":"/dnd-interface [type] [--type sortable|kanban|grid] [--accessible]","example":"/dnd-interface kanban --type kanban --accessible","tags":["dnd-kit","drag-drop","kanban","sortable"]},
  {"id":"fe-014","title":"Storybook Component Docs","command":"/storybook","platform":"Frontend","category":"Frontend & UI","type":"Documentation","summary":"Setup Storybook 8 with autodocs, visual testing, and interaction tests","description":"Configure Storybook 8: autodocs generation, Controls addon, Interactions for play functions, Chromatic visual regression testing, and MSW for API mocking","syntax":"/storybook [component] [--visual-testing] [--interactions] [--msw]","example":"/storybook Button --visual-testing --interactions --msw","tags":["storybook","documentation","testing","components"]},
  {"id":"fe-015","title":"CSS Grid Layout Master","command":"/css-grid","platform":"Frontend","category":"Frontend & UI","type":"Layout","summary":"Create complex CSS Grid layouts: masonry, magazine, dashboard","description":"Build advanced CSS Grid layouts: subgrid, masonry layout, magazine-style grids, auto-fit/auto-fill, named grid areas, and responsive without media queries","syntax":"/css-grid [layout-type] [--responsive] [--subgrid] [--areas]","example":"/css-grid magazine --responsive --subgrid --areas","tags":["css-grid","layout","responsive","css"]},

  # =================== ALGORITHMIQUE (30 skills) ===================
  {"id":"al-001","title":"Binary Search Variants","command":"/binary-search","platform":"Algorithm","category":"Algorithmique","type":"Search","summary":"Implement binary search variants: leftmost, rightmost, rotated array","description":"Master binary search: classic, find first/last occurrence, search in rotated sorted array, peak element, minimized maximum, and answer binary search pattern","syntax":"/binary-search [variant] [--complexity O(log n)]","example":"/binary-search rotated-array","tags":["binary-search","algorithm","leetcode","array"]},
  {"id":"al-002","title":"Dynamic Programming Solver","command":"/dp-solve","platform":"Algorithm","category":"Algorithmique","type":"DP","summary":"Solve DP problems: memoization, tabulation, space optimization","description":"Apply DP patterns: 0/1 knapsack, LCS, LIS, matrix chain, coin change, palindrome partitioning, digit DP, broken profile DP, and bitmasked DP","syntax":"/dp-solve [problem-type] [--approach memo|tabulation] [--optimize space]","example":"/dp-solve knapsack --approach tabulation --optimize space","tags":["dynamic-programming","dp","algorithm","optimization"]},
  {"id":"al-003","title":"Graph Traversal Suite","command":"/graph-traverse","platform":"Algorithm","category":"Algorithmique","type":"Graph","summary":"BFS, DFS, Dijkstra, Bellman-Ford, Floyd-Warshall, A* implementations","description":"Complete graph algorithms: BFS/DFS with applications, Dijkstra's shortest path, Bellman-Ford negative cycles, Floyd-Warshall all-pairs, A* heuristic search","syntax":"/graph-traverse [algorithm] [--weighted] [--directed] [--negative-weights]","example":"/graph-traverse dijkstra --weighted --directed","tags":["graph","bfs","dfs","dijkstra","algorithm"]},
  {"id":"al-004","title":"Sorting Algorithms Lab","command":"/sort-lab","platform":"Algorithm","category":"Algorithmique","type":"Sorting","summary":"Implement and benchmark: QuickSort, MergeSort, HeapSort, RadixSort, TimSort","description":"Complete sorting suite with visualizer: QuickSort (3-way, dual-pivot), MergeSort (iterative), HeapSort, RadixSort, CountingSort, TimSort with performance benchmarks","syntax":"/sort-lab [algorithm] [--benchmark] [--visualize] [--input random|sorted|reversed]","example":"/sort-lab quicksort --benchmark --input random","tags":["sorting","algorithm","quicksort","mergesort"]},
  {"id":"al-005","title":"Tree Algorithms Collection","command":"/tree-algo","platform":"Algorithm","category":"Algorithmique","type":"Tree","summary":"BST operations, AVL, Red-Black Tree, Segment Tree, Fenwick Tree","description":"Tree algorithm library: BST CRUD, AVL self-balancing, Red-Black tree, Segment tree (range queries), Fenwick/BIT (prefix sums), Trie, Suffix Tree","syntax":"/tree-algo [type] [--operations insert,delete,search,range] [--balanced]","example":"/tree-algo segment-tree --operations range-sum,range-min","tags":["tree","bst","segment-tree","fenwick","trie"]},
  {"id":"al-006","title":"Sliding Window Technique","command":"/sliding-window","platform":"Algorithm","category":"Algorithmique","type":"Pattern","summary":"Fixed/variable sliding window: max subarray, longest substring, minimum window","description":"Apply sliding window: fixed-size window (max sum), variable-size (longest substring without repeat), monotonic deque, two-pointer technique, and shrinkable window","syntax":"/sliding-window [problem] [--window fixed|variable] [--deque]","example":"/sliding-window longest-substring --window variable","tags":["sliding-window","two-pointer","array","algorithm"]},
  {"id":"al-007","title":"Greedy Algorithm Designer","command":"/greedy","platform":"Algorithm","category":"Algorithmique","type":"Greedy","summary":"Apply greedy strategies: interval scheduling, Huffman coding, activity selection","description":"Implement greedy algorithms: interval scheduling maximization, Huffman encoding, activity selection, fractional knapsack, job sequencing, and proof of optimality","syntax":"/greedy [problem] [--prove-optimal]","example":"/greedy interval-scheduling --prove-optimal","tags":["greedy","algorithm","optimization","intervals"]},
  {"id":"al-008","title":"Union-Find / DSU","command":"/union-find","platform":"Algorithm","category":"Algorithmique","type":"Data Structure","summary":"Disjoint Set Union with path compression and union by rank","description":"Implement Union-Find with path compression + union by rank, offline LCA, Kruskal's MST, connected components, percolation, and bipartite detection","syntax":"/union-find [application] [--path-compression] [--weighted]","example":"/union-find kruskal-mst --path-compression --weighted","tags":["union-find","dsu","graph","mst","algorithm"]},
  {"id":"al-009","title":"Backtracking Framework","command":"/backtrack","platform":"Algorithm","category":"Algorithmique","type":"Search","summary":"Systematic backtracking: N-Queens, Sudoku solver, permutations, combinations","description":"Build backtracking solutions: N-Queens, Sudoku, word search, phone number permutations, subsets, combination sum, and pruning strategies for optimization","syntax":"/backtrack [problem] [--prune] [--visualize]","example":"/backtrack sudoku --prune --visualize","tags":["backtracking","recursion","dfs","algorithm"]},
  {"id":"al-010","title":"String Algorithm Toolkit","command":"/string-algo","platform":"Algorithm","category":"Algorithmique","type":"String","summary":"KMP, Rabin-Karp, Z-algorithm, Manacher's, Aho-Corasick pattern matching","description":"Advanced string algorithms: KMP pattern search, Rabin-Karp rolling hash, Z-function, Manacher's palindrome, Aho-Corasick multi-pattern, suffix array + LCP","syntax":"/string-algo [algorithm] [--pattern] [--multi-pattern]","example":"/string-algo aho-corasick --multi-pattern","tags":["kmp","string","pattern-matching","algorithm"]},
  {"id":"al-011","title":"Math Algorithms","command":"/math-algo","platform":"Algorithm","category":"Algorithmique","type":"Math","summary":"Number theory: Sieve of Eratosthenes, GCD/LCM, modular exponentiation, FFT","description":"Mathematical algorithms: prime sieve, GCD/LCM, extended Euclidean, modular exponentiation, Chinese Remainder Theorem, matrix exponentiation, Fast Fourier Transform","syntax":"/math-algo [algorithm] [--modular-arithmetic] [--big-numbers]","example":"/math-algo sieve --limit 1000000","tags":["math","number-theory","sieve","fft","algorithm"]},
  {"id":"al-012","title":"Heap & Priority Queue","command":"/heap-pq","platform":"Algorithm","category":"Algorithmique","type":"Data Structure","summary":"Min-heap, max-heap, indexed priority queue for Dijkstra and scheduling","description":"Priority queue implementations: binary heap, indexed heap for Dijkstra, k-way merge, median maintenance (two heaps), task scheduling, and heap sort","syntax":"/heap-pq [type] [--indexed] [--application dijkstra|kth-largest|median]","example":"/heap-pq min-heap --indexed --application dijkstra","tags":["heap","priority-queue","algorithm","data-structure"]},

  # =================== DATABASE (30 skills) ===================
  {"id":"db-001","title":"PostgreSQL Index Optimizer","command":"/pg-index","platform":"Database","category":"Database","type":"Optimization","summary":"Analyze and create optimal PostgreSQL indexes: B-tree, GiST, BRIN, partial","description":"PostgreSQL indexing mastery: analyze slow queries with EXPLAIN ANALYZE, create B-tree, GiST, GIN, BRIN indexes, partial/covering indexes, and multi-column composite indexes","syntax":"/pg-index [table] [--analyze] [--type btree|gist|gin|brin] [--partial condition]","example":"/pg-index users_table --analyze --type btree --partial 'active = true'","tags":["postgresql","indexes","optimization","sql"]},
  {"id":"db-002","title":"pgvector Semantic Search","command":"/pgvector","platform":"Database","category":"Database","type":"AI","summary":"Add vector similarity search to PostgreSQL with pgvector extension","description":"Implement semantic search with pgvector: store embeddings, create IVFFlat/HNSW indexes, cosine/L2/inner product similarity, and hybrid keyword+semantic search","syntax":"/pgvector [table] [--dims 1536] [--index hnsw|ivfflat] [--metric cosine|l2]","example":"/pgvector documents --dims 1536 --index hnsw --metric cosine","tags":["pgvector","semantic-search","embeddings","postgresql"]},
  {"id":"db-003","title":"MongoDB Aggregation Pipeline","command":"/mongo-agg","platform":"Database","category":"Database","type":"Query","summary":"Build complex MongoDB aggregation pipelines: $lookup, $unwind, $group, $facet","description":"Master MongoDB aggregation: multi-stage pipeline, $lookup joins, $unwind arrays, $group statistics, $facet multi-faceted search, $merge output, and Atlas Search","syntax":"/mongo-agg [collection] [--stages] [--atlas-search] [--explain]","example":"/mongo-agg orders --stages lookup,group,facet --explain","tags":["mongodb","aggregation","nosql","pipeline"]},
  {"id":"db-004","title":"Redis Data Structures","command":"/redis-ds","platform":"Database","category":"Database","type":"Cache","summary":"Use Redis advanced data structures: Sorted Sets, Streams, Bloom Filters, HLL","description":"Redis beyond cache: Sorted Sets for leaderboards, Streams for event log, Bloom Filter for membership, HyperLogLog for cardinality, RedisSearch, and RedisJSON","syntax":"/redis-ds [structure] [--use-case leaderboard|stream|search]","example":"/redis-ds sorted-set --use-case leaderboard","tags":["redis","sorted-sets","streams","cache","nosql"]},
  {"id":"db-005","title":"Prisma ORM Schema Master","command":"/prisma-schema","platform":"Database","category":"Database","type":"ORM","summary":"Design Prisma schema with relations, indexes, full-text search, and middleware","description":"Build Prisma schema: one-to-many, many-to-many with join tables, composite keys, @@index, @@unique, full-text search, soft delete middleware, and multi-tenant support","syntax":"/prisma-schema [model] [--relations] [--soft-delete] [--multi-tenant]","example":"/prisma-schema Post --relations User,Tag --soft-delete --multi-tenant","tags":["prisma","orm","schema","postgresql"]},
  {"id":"db-006","title":"SQL Window Functions","command":"/sql-window","platform":"Database","category":"Database","type":"Analytics","summary":"Master SQL window functions: ROW_NUMBER, RANK, LAG/LEAD, running totals","description":"Advanced window functions: ROW_NUMBER, RANK, DENSE_RANK, NTILE, LAG/LEAD for time series, running totals with SUM OVER, moving averages, and frame specification","syntax":"/sql-window [function] [--partition-by] [--order-by] [--frame rows|range]","example":"/sql-window rank --partition-by department --order-by salary DESC","tags":["sql","window-functions","analytics","postgresql"]},
  {"id":"db-007","title":"Database Sharding Strategy","command":"/db-shard","platform":"Database","category":"Database","type":"Architecture","summary":"Design database sharding: horizontal partitioning, shard keys, routing","description":"Implement database sharding: horizontal vs vertical partitioning, shard key selection, consistent hashing, routing layer, cross-shard queries, and rebalancing strategies","syntax":"/db-shard [strategy] [--key user_id|geo|hash] [--shards 16]","example":"/db-shard consistent-hashing --key user_id --shards 16","tags":["sharding","database","scalability","architecture"]},
  {"id":"db-008","title":"Elasticsearch Full-Text Search","command":"/elastic-search","platform":"Database","category":"Database","type":"Search","summary":"Build Elasticsearch queries: fuzzy search, facets, highlighting, aggregations","description":"Elasticsearch mastery: index mapping, analyzers/tokenizers, multi-match query, fuzzy search, geo-distance, aggregation buckets/metrics, and suggestion completion","syntax":"/elastic-search [query-type] [--index] [--fuzzy] [--highlight] [--aggs]","example":"/elastic-search multi-match --fuzzy --highlight --aggs facets","tags":["elasticsearch","full-text-search","search","analytics"]},
  {"id":"db-009","title":"ClickHouse Analytics Queries","command":"/clickhouse","platform":"Database","category":"Database","type":"Analytics","summary":"Write ClickHouse OLAP queries for real-time analytics at scale","description":"ClickHouse for analytics: MergeTree engine, materialized views, AggregatingMergeTree, distributed tables, ReplacingMergeTree for deduplication, and time-series analytics","syntax":"/clickhouse [query-type] [--engine MergeTree|Aggregating] [--materialized-view]","example":"/clickhouse time-series --engine MergeTree --materialized-view","tags":["clickhouse","analytics","olap","time-series"]},
  {"id":"db-010","title":"Database Connection Pool","command":"/db-pool","platform":"Database","category":"Database","type":"Performance","summary":"Configure PgBouncer/HikariCP connection pooling for high-throughput apps","description":"Set up connection pooling: PgBouncer transaction mode, HikariCP for Java, asyncpg pool for Python, pool sizing formulas, pool exhaustion handling, and monitoring","syntax":"/db-pool [pooler] [--size] [--mode transaction|session] [--monitor]","example":"/db-pool pgbouncer --size 20 --mode transaction --monitor","tags":["connection-pool","pgbouncer","postgresql","performance"]},

  # =================== SECURITY (30 skills) ===================
  {"id":"sec-001","title":"OWASP Top 10 Auditor","command":"/owasp-audit","platform":"Security","category":"Security","type":"Audit","summary":"Systematic audit for OWASP Top 10 vulnerabilities in your codebase","description":"Scan for OWASP Top 10: injection flaws, broken auth, XSS, IDOR, security misconfig, SSRF, XXE, insecure deserialization, vulnerable components, and logging failures","syntax":"/owasp-audit [target] [--top10] [--report html|json] [--fix]","example":"/owasp-audit src/ --top10 --report html --fix","tags":["owasp","security","audit","vulnerabilities"]},
  {"id":"sec-002","title":"SQL Injection Prevention","command":"/sqli-fix","platform":"Security","category":"Security","type":"Vulnerability","summary":"Detect and fix SQL injection: parameterized queries, ORM usage, input sanitization","description":"Prevent SQLi: audit raw SQL concatenation, convert to parameterized queries, ORM safe methods, stored procedures review, WAF rules, and testing with SQLMap","syntax":"/sqli-fix [file] [--auto-fix] [--test sqlmap]","example":"/sqli-fix src/db/ --auto-fix","tags":["sql-injection","security","owasp","database"]},
  {"id":"sec-003","title":"XSS Prevention Shield","command":"/xss-fix","platform":"Security","category":"Security","type":"Vulnerability","summary":"Prevent XSS: CSP headers, DOMPurify, output encoding, HttpOnly cookies","description":"Stop XSS attacks: Content Security Policy configuration, DOMPurify for rich text, output encoding library, HttpOnly/SameSite cookies, Trusted Types API","syntax":"/xss-fix [type] [--csp] [--trusted-types] [--sanitize]","example":"/xss-fix stored-xss --csp strict --trusted-types","tags":["xss","csp","security","web"]},
  {"id":"sec-004","title":"Secret Scanner","command":"/scan-secrets","platform":"Security","category":"Security","type":"Scanning","summary":"Scan codebase for leaked secrets: API keys, passwords, private keys in git history","description":"Detect leaked secrets: TruffleHog, detect-secrets, GitLeaks integration, AWS key patterns, regex patterns for 200+ secret types, pre-commit hook, and remediation","syntax":"/scan-secrets [--history] [--provider aws|github|stripe] [--fix]","example":"/scan-secrets --history --provider aws,github,stripe","tags":["secrets","security","gitguardian","scanning"]},
  {"id":"sec-005","title":"HTTPS & TLS Hardening","command":"/tls-harden","platform":"Security","category":"Security","type":"Hardening","summary":"Configure TLS 1.3, HSTS, certificate pinning, and cipher suite optimization","description":"TLS hardening: enforce TLS 1.3, disable weak ciphers, HSTS with preload, OCSP stapling, certificate transparency, Let's Encrypt automation, and SSL Labs A+ rating","syntax":"/tls-harden [server] [--tls-version 1.3] [--hsts] [--cert-pinning]","example":"/tls-harden nginx --tls-version 1.3 --hsts --cert-pinning","tags":["tls","https","ssl","security","hardening"]},
  {"id":"sec-006","title":"Container Security Scanner","command":"/container-sec","platform":"Security","category":"Security","type":"DevSecOps","summary":"Scan Docker images for vulnerabilities with Trivy, Snyk, Grype","description":"Secure containers: Trivy vulnerability scan, non-root user enforcement, read-only filesystem, distroless base images, Snyk container scanning, and SBOM generation","syntax":"/container-sec [image] [--scanner trivy|snyk|grype] [--severity HIGH,CRITICAL] [--sbom]","example":"/container-sec my-app:latest --scanner trivy --severity HIGH,CRITICAL --sbom","tags":["docker","container","security","trivy","devsecops"]},
  {"id":"sec-007","title":"API Security Hardening","command":"/api-sec","platform":"Security","category":"Security","type":"Hardening","summary":"Secure REST APIs: auth, rate limiting, input validation, CORS, security headers","description":"API security checklist: JWT validation, OAuth 2.0 scopes, rate limiting per endpoint, Helmet.js headers, CORS whitelist, request size limits, and schema validation","syntax":"/api-sec [framework] [--auth jwt|oauth2] [--headers] [--rate-limit] [--cors]","example":"/api-sec express --auth jwt --headers --rate-limit --cors whitelist","tags":["api","security","jwt","cors","headers"]},
  {"id":"sec-008","title":"Dependency Vulnerability Audit","command":"/dep-audit","platform":"Security","category":"Security","type":"Scanning","summary":"Audit npm/pip/maven dependencies for known CVEs and supply chain risks","description":"Dependency security: npm audit, pip-audit, Dependabot config, Supply chain attack detection, license compliance, and automated PR creation for patches","syntax":"/dep-audit [ecosystem] [--fix] [--dependabot] [--license-check]","example":"/dep-audit npm --fix --dependabot --license-check","tags":["dependencies","cve","security","supply-chain","npm"]},
  {"id":"sec-009","title":"Zero Trust Access Policy","command":"/zero-trust","platform":"Security","category":"Security","type":"Architecture","summary":"Design Zero Trust network: mTLS, service mesh, BeyondCorp access policies","description":"Implement Zero Trust: mutual TLS between services, service mesh (Istio/Linkerd), BeyondCorp model, short-lived certificates, SPIFFE/SPIRE identity, and policy as code","syntax":"/zero-trust [component] [--mesh istio|linkerd] [--mtls] [--spiffe]","example":"/zero-trust api-service --mesh istio --mtls --spiffe","tags":["zero-trust","mtls","service-mesh","istio","security"]},
  {"id":"sec-010","title":"Penetration Testing Checklist","command":"/pentest","platform":"Security","category":"Security","type":"Testing","summary":"Structured pentest checklist: recon, exploitation, privilege escalation, reporting","description":"Systematic penetration testing: OSINT recon, network scanning, web app testing (OWASP), API fuzzing, auth bypass attempts, privilege escalation, and finding report template","syntax":"/pentest [target-type] [--phase recon|exploit|report] [--scope web|api|infra]","example":"/pentest web-app --phase recon --scope web,api","tags":["pentest","security","ethical-hacking","owasp"]},

  # =================== SCRAPING (20 skills) ===================
  {"id":"sc-001","title":"Playwright Stealth Scraper","command":"/playwright-scrape","platform":"Scraping","category":"Scraping","type":"Browser","summary":"Build undetectable Playwright scrapers with stealth plugins and anti-bot bypass","description":"Playwright scraping: stealth plugin to hide automation, random user agents, fingerprint randomization, mouse movement simulation, CAPTCHA solving (2captcha), and proxy rotation","syntax":"/playwright-scrape [url] [--stealth] [--proxy] [--captcha 2captcha]","example":"/playwright-scrape https://example.com --stealth --proxy residential","tags":["playwright","scraping","stealth","anti-bot"]},
  {"id":"sc-002","title":"Scrapy Spider Factory","command":"/scrapy-spider","platform":"Scraping","category":"Scraping","type":"Framework","summary":"Generate Scrapy spiders with middlewares, pipelines, and distributed crawling","description":"Build production Scrapy spiders: item pipelines (MongoDB, PostgreSQL), download middlewares, rotating proxies, AutoThrottle, Splash JS rendering, and Scrapy-Splash","syntax":"/scrapy-spider [domain] [--pipeline mongo|postgres] [--js-render] [--distributed]","example":"/scrapy-spider ecommerce.com --pipeline postgres --js-render --distributed","tags":["scrapy","python","spider","crawling"]},
  {"id":"sc-003","title":"BeautifulSoup Parser","command":"/bs4-parse","platform":"Scraping","category":"Scraping","type":"Parsing","summary":"Parse HTML/XML with BeautifulSoup4: CSS selectors, XPath, structured data extraction","description":"HTML parsing with BS4: CSS selectors, XPath queries, structured data (JSON-LD, microdata, OpenGraph), table extraction, pagination handling, and data normalization","syntax":"/bs4-parse [url] [--selector css|xpath] [--structured-data] [--paginate]","example":"/bs4-parse https://news.site --selector css --structured-data --paginate","tags":["beautifulsoup","python","html-parsing","scraping"]},
  {"id":"sc-004","title":"Data Pipeline ETL Scraper","command":"/etl-scrape","platform":"Scraping","category":"Scraping","type":"ETL","summary":"Build scraping ETL pipeline: extract, transform, and load to database/storage","description":"Complete scraping ETL: scheduled scraping with APScheduler/Celery, data validation with Pydantic, deduplication, PostgreSQL/MongoDB storage, and dashboard monitoring","syntax":"/etl-scrape [source] [--schedule cron] [--validate pydantic] [--store postgres|mongo]","example":"/etl-scrape product-catalog --schedule '0 */6 * * *' --validate pydantic --store postgres","tags":["etl","scraping","pipeline","celery","postgresql"]},
  {"id":"sc-005","title":"API Reverse Engineer","command":"/api-reverse","platform":"Scraping","category":"Scraping","type":"Analysis","summary":"Intercept and reverse-engineer hidden APIs from web apps using browser devtools","description":"Reverse engineer hidden APIs: Playwright network interception, HAR file analysis, JWT token extraction, GraphQL introspection, WebSocket message capture, and API reconstruction","syntax":"/api-reverse [url] [--intercept] [--graphql] [--websocket] [--export postman]","example":"/api-reverse https://spa-app.com --intercept --graphql --export postman","tags":["api-reverse","scraping","network","playwright","devtools"]},

  # =================== VIDEO (20 skills) ===================
  {"id":"vid-001","title":"FFmpeg Video Processor","command":"/ffmpeg","platform":"Video","category":"Video","type":"Processing","summary":"FFmpeg commands: transcode, trim, merge, add subtitles, change resolution","description":"FFmpeg master commands: video transcoding, segment trimming, concat demuxer merging, subtitle burning, resolution scaling, audio extraction, thumbnail generation, and HLS streaming","syntax":"/ffmpeg [operation] [--input] [--output-format mp4|webm|hls] [--quality crf 23]","example":"/ffmpeg transcode --input video.mov --output-format mp4 --quality crf 18","tags":["ffmpeg","video","transcode","processing"]},
  {"id":"vid-002","title":"HLS Streaming Setup","command":"/hls-stream","platform":"Video","category":"Video","type":"Streaming","summary":"Configure HLS adaptive bitrate streaming: segment generation, CDN delivery","description":"HLS setup: FFmpeg segmentation, multiple quality levels (360p/720p/1080p), m3u8 playlist generation, CDN distribution (CloudFront/Cloudflare), and Video.js player integration","syntax":"/hls-stream [video] [--qualities 360,720,1080] [--cdn cloudfront|cloudflare] [--segment 6]","example":"/hls-stream video.mp4 --qualities 360,720,1080 --cdn cloudfront --segment 6","tags":["hls","streaming","adaptive-bitrate","cdn","video"]},
  {"id":"vid-003","title":"Video Thumbnail Generator","command":"/thumbnail-gen","platform":"Video","category":"Video","type":"Processing","summary":"Auto-generate video thumbnails with intelligent scene detection","description":"Thumbnail generation: FFmpeg scene detection, timestamp-based extraction, smart frame selection (avoiding black frames), batch processing, and WebP optimization","syntax":"/thumbnail-gen [video] [--method scene|timestamp|interval] [--count 5] [--format webp]","example":"/thumbnail-gen video.mp4 --method scene --count 5 --format webp","tags":["thumbnail","ffmpeg","video","image-processing"]},
  {"id":"vid-004","title":"Screen Recorder CLI","command":"/screen-record","platform":"Video","category":"Video","type":"Capture","summary":"Record screen, webcam, audio with FFmpeg: demos, tutorials, presentations","description":"Screen capture: FFmpeg avfoundation capture (macOS), x11grab (Linux), combined screen+webcam overlay, system audio mixing, mouse cursor highlighting, and MP4 output","syntax":"/screen-record [--screen] [--webcam] [--audio system|mic] [--quality high]","example":"/screen-record --screen --webcam --audio system --quality high","tags":["screen-record","ffmpeg","capture","screencast"]},
  {"id":"vid-005","title":"Video AI Analyzer","command":"/video-ai","platform":"Video","category":"Video","type":"AI","summary":"Analyze video content with Gemini Vision: scene detection, transcription, summary","description":"AI video analysis: Gemini 2.0 Flash for video understanding, automatic transcription with Whisper, scene segmentation, content moderation, highlight extraction","syntax":"/video-ai [video] [--analyze scenes|transcript|summary] [--model gemini|whisper]","example":"/video-ai lecture.mp4 --analyze scenes,transcript,summary --model gemini","tags":["video-ai","gemini","whisper","transcription","analysis"]},

  # =================== IMAGE (20 skills) ===================
  {"id":"img-001","title":"Sharp Image Pipeline","command":"/sharp","platform":"Image","category":"Image","type":"Processing","summary":"High-performance image processing with Sharp: resize, compress, convert, watermark","description":"Sharp image pipeline: resize with smart crop, WebP/AVIF conversion, quality optimization, blur/sharpen filters, watermark overlay, metadata stripping, and batch processing","syntax":"/sharp [operation] [--format webp|avif|jpg] [--quality 80] [--resize width x height]","example":"/sharp optimize --format webp --quality 80 --resize 1920x1080","tags":["sharp","image","webp","avif","optimization"]},
  {"id":"img-002","title":"Stable Diffusion Prompter","command":"/sd-prompt","platform":"Image","category":"Image","type":"AI Generation","summary":"Engineer Stable Diffusion prompts: style, lighting, composition, negative prompts","description":"SD prompt engineering: style modifiers (cinematic, illustration, photography), lighting (golden hour, studio), composition (rule of thirds), LoRA concepts, and CLIP guidance","syntax":"/sd-prompt [subject] [--style cinematic|illustration|photography] [--lighting] [--negative]","example":"/sd-prompt portrait --style cinematic --lighting golden-hour --negative blur,low-quality","tags":["stable-diffusion","image-generation","prompt-engineering","ai"]},
  {"id":"img-003","title":"Image OCR Extractor","command":"/ocr","platform":"Image","category":"Image","type":"Extraction","summary":"Extract text from images with Tesseract or Gemini Vision OCR","description":"OCR pipeline: Tesseract with language packs, Gemini Vision for complex layouts, table extraction from images, receipt parsing, ID document OCR, and structured output","syntax":"/ocr [image] [--engine tesseract|gemini] [--lang en,fr,he] [--type document|table|receipt]","example":"/ocr invoice.jpg --engine gemini --type table","tags":["ocr","tesseract","gemini","text-extraction","image"]},
  {"id":"img-004","title":"Background Remover","command":"/bg-remove","platform":"Image","category":"Image","type":"AI","summary":"Remove image backgrounds with rembg/SAM: products, portraits, logos","description":"Background removal: rembg (U²-Net) for bulk processing, Segment Anything Model (SAM) for precise cutouts, alpha channel output, transparent PNG, and batch folder processing","syntax":"/bg-remove [image] [--model rembg|sam] [--output png] [--batch folder/]","example":"/bg-remove product.jpg --model rembg --output png","tags":["background-removal","rembg","sam","image","ai"]},

  # =================== LOGO & BRANDING (15 skills) ===================
  {"id":"logo-001","title":"SVG Logo Generator","command":"/svg-logo","platform":"Design","category":"Logo & Branding","type":"Vector","summary":"Generate scalable SVG logos with geometric shapes, gradients, and typography","description":"SVG logo creation: geometric primitives, GSAP animations, gradient definitions, text paths, clip masks, responsive viewBox, and multi-format export (SVG, PNG, ICO, WebP)","syntax":"/svg-logo [concept] [--style minimal|bold|gradient|3d] [--animate] [--export all]","example":"/svg-logo tech-startup --style gradient --animate --export all","tags":["svg","logo","design","vector","branding"]},
  {"id":"logo-002","title":"Brand Identity System","command":"/brand-system","platform":"Design","category":"Logo & Branding","type":"Brand","summary":"Create complete brand identity: colors, typography, spacing, component library","description":"Brand system: primary/secondary color palette with hex/HSL/RGB, typography scale (font pairs), spacing system, logo usage rules, dark/light variants, and style guide","syntax":"/brand-system [brand-name] [--colors] [--fonts] [--components] [--dark-mode]","example":"/brand-system KortexDeck --colors cyan,indigo --fonts inter,mono --dark-mode","tags":["branding","design-system","typography","colors","identity"]},
  {"id":"logo-003","title":"App Icon Generator","command":"/app-icon","platform":"Design","category":"Logo & Branding","type":"Icon","summary":"Generate app icons for iOS, Android, PWA in all required sizes","description":"App icon factory: iOS (1024x1024 to 20x20), Android (adaptive icon with foreground/background layers), PWA manifest icons, macOS dock icon, and favicon set","syntax":"/app-icon [base-image] [--platforms ios|android|pwa|macos] [--adaptive]","example":"/app-icon logo.png --platforms ios,android,pwa --adaptive","tags":["app-icon","ios","android","pwa","design"]},
  {"id":"logo-004","title":"Favicon Complete Kit","command":"/favicon","platform":"Design","category":"Logo & Branding","type":"Web","summary":"Generate complete favicon kit: ICO, PNG, SVG, web manifest, HTML tags","description":"Favicon kit: 16x16, 32x32, 48x48 ICO, 180x180 apple-touch-icon, 192x192+512x512 PNG for PWA, SVG favicon, browserconfig.xml, site.webmanifest, and meta tags","syntax":"/favicon [image] [--light-dark] [--theme-color #000000]","example":"/favicon logo.svg --light-dark --theme-color '#06b6d4'","tags":["favicon","pwa","web","icons","branding"]},

  # =================== NAME & DOMAIN (15 skills) ===================
  {"id":"nd-001","title":"Domain Name Generator","command":"/domain-gen","platform":"Domain","category":"Name & Domain","type":"Branding","summary":"Generate brandable domain names: portmanteau, keyword combinations, CVCV patterns","description":"Domain name generation: keyword analysis, portmanteau synthesis, CVCV (pronounceable) patterns, .com/.io/.dev/.ai availability check, Levenshtein similarity, and trademark proximity","syntax":"/domain-gen [keywords] [--tld com|io|dev|ai] [--style portmanteau|descriptive|abstract] [--check]","example":"/domain-gen ai automation tools --tld io,dev,ai --style portmanteau --check","tags":["domain","naming","branding","startup","tld"]},
  {"id":"nd-002","title":"WHOIS & DNS Auditor","command":"/dns-audit","platform":"Domain","category":"Name & Domain","type":"DNS","summary":"Audit DNS records: A, AAAA, MX, SPF, DKIM, DMARC, CAA, DNSSEC","description":"DNS security audit: check all record types, SPF/DKIM/DMARC email authentication, CAA for certificate authorities, DNSSEC validation, DNS propagation check, and security recommendations","syntax":"/dns-audit [domain] [--records all|email|security] [--dnssec] [--propagation]","example":"/dns-audit cohenwebstudio.com --records all --dnssec --propagation","tags":["dns","whois","security","email","domain"]},
  {"id":"nd-003","title":"SaaS Name Validator","command":"/saas-name","platform":"Domain","category":"Name & Domain","type":"Validation","summary":"Validate SaaS product names: trademark search, social media availability, linguistics","description":"Name validation pipeline: USPTO trademark search, social media handle availability (@twitter, @instagram, GitHub org), linguistic analysis (meaning in 10 languages), and phonetic scoring","syntax":"/saas-name [name] [--trademark] [--social] [--linguistics] [--phonetic]","example":"/saas-name KortexDeck --trademark --social github,twitter --linguistics --phonetic","tags":["naming","trademark","saas","branding","validation"]},

  # =================== ARCHITECTURE (25 skills) ===================
  {"id":"arch-001","title":"Event-Driven Architecture","command":"/event-driven","platform":"Architecture","category":"Architecture","type":"Pattern","summary":"Design event-driven systems: event sourcing, CQRS, saga pattern, outbox","description":"Event-driven architecture: event sourcing with event store, CQRS read/write model separation, saga pattern for distributed transactions, transactional outbox, and event versioning","syntax":"/event-driven [pattern] [--broker kafka|rabbitmq] [--cqrs] [--saga]","example":"/event-driven order-system --broker kafka --cqrs --saga","tags":["event-sourcing","cqrs","saga","kafka","architecture"]},
  {"id":"arch-002","title":"Clean Architecture Scaffold","command":"/clean-arch","platform":"Architecture","category":"Architecture","type":"Pattern","summary":"Scaffold Clean Architecture layers: entities, use cases, adapters, frameworks","description":"Clean Architecture implementation: entities (business rules), use cases (application logic), interface adapters (controllers/presenters), frameworks layer, dependency inversion, and testing strategy","syntax":"/clean-arch [project] [--lang go|node|python|java] [--layers all]","example":"/clean-arch ecommerce --lang go --layers all","tags":["clean-architecture","hexagonal","ddd","solid","architecture"]},
  {"id":"arch-003","title":"Hexagonal / Ports & Adapters","command":"/hexagonal","platform":"Architecture","category":"Architecture","type":"Pattern","summary":"Implement hexagonal architecture: ports, adapters, domain isolation","description":"Hexagonal architecture: domain core (no external dependencies), primary ports (use cases), secondary ports (repository interfaces), primary adapters (REST/CLI), secondary adapters (DB/queue)","syntax":"/hexagonal [service] [--ports rest,cli] [--adapters db,queue,cache]","example":"/hexagonal user-service --ports rest,grpc --adapters postgres,redis,kafka","tags":["hexagonal","ports-adapters","ddd","clean-code","architecture"]},
  {"id":"arch-004","title":"DDD Domain Modeler","command":"/ddd-model","platform":"Architecture","category":"Architecture","type":"DDD","summary":"Model domain: aggregates, entities, value objects, bounded contexts, ubiquitous language","description":"DDD modeling: identify bounded contexts, design aggregates with invariants, value objects (immutable), domain events, repositories, domain services, and anti-corruption layer","syntax":"/ddd-model [domain] [--contexts] [--aggregates] [--events] [--language ubiquitous]","example":"/ddd-model e-commerce --contexts order,inventory,payment --aggregates --events","tags":["ddd","domain-driven-design","aggregates","bounded-context","architecture"]},
  {"id":"arch-005","title":"API Versioning Strategy","command":"/api-versioning","platform":"Architecture","category":"Architecture","type":"Design","summary":"Implement API versioning: URL path, header, content negotiation, sunset policy","description":"API versioning strategies: URL path versioning (/v1, /v2), Accept header versioning, custom header, version sunset policy, backward compatibility rules, and migration guides","syntax":"/api-versioning [strategy] [--deprecation-policy] [--sunset-header] [--migrate]","example":"/api-versioning url-path --deprecation-policy 6months --sunset-header","tags":["api-versioning","rest","compatibility","architecture","design"]},

  # =================== FRAMEWORK (20 skills) ===================
  {"id":"fw-001","title":"Django REST Framework Pro","command":"/django-drf","platform":"Framework","category":"Framework","type":"Backend","summary":"Build Django DRF APIs: serializers, ViewSets, authentication, permissions, filters","description":"Django REST Framework mastery: ModelSerializer, ViewSets with router, JWT via djangorestframework-simplejwt, DjangoFilterBackend, Swagger via drf-spectacular, and celery tasks","syntax":"/django-drf [resource] [--auth jwt|session] [--filter] [--swagger] [--celery]","example":"/django-drf Product --auth jwt --filter --swagger --celery","tags":["django","drf","python","rest","api"]},
  {"id":"fw-002","title":"Spring Boot Microservice","command":"/spring-boot","platform":"Framework","category":"Framework","type":"Backend","summary":"Generate Spring Boot 3 microservices: REST, JPA, Security, Actuator, Docker","description":"Spring Boot 3 scaffold: REST controllers, Spring Data JPA with Liquibase, Spring Security OAuth2, Actuator health/metrics, MapStruct DTOs, and Docker Compose dev setup","syntax":"/spring-boot [service] [--db postgres|mysql] [--security oauth2|jwt] [--actuator]","example":"/spring-boot user-service --db postgres --security jwt --actuator","tags":["spring-boot","java","microservice","jpa","security"]},
  {"id":"fw-003","title":"NestJS Module Builder","command":"/nestjs-module","platform":"Framework","category":"Framework","type":"Backend","summary":"Build NestJS modules: controllers, services, guards, interceptors, pipes","description":"NestJS module architecture: feature modules, dependency injection, guards (JWT/RBAC), interceptors (logging/transform), pipes (validation), exception filters, and Swagger decorator","syntax":"/nestjs-module [module] [--guard jwt|rbac] [--interceptor] [--swagger]","example":"/nestjs-module auth --guard jwt,rbac --interceptor logging --swagger","tags":["nestjs","typescript","node","dependency-injection","guards"]},
  {"id":"fw-004","title":"Laravel API Blueprint","command":"/laravel-api","platform":"Framework","category":"Framework","type":"Backend","summary":"Build Laravel REST APIs: Eloquent resources, policies, form requests, Sanctum","description":"Laravel API: Eloquent API resources, model policies, form request validation, Laravel Sanctum for SPA auth, API versioning, queue jobs, and Laravel Telescope debugging","syntax":"/laravel-api [resource] [--auth sanctum|passport] [--policy] [--queue]","example":"/laravel-api Product --auth sanctum --policy --queue","tags":["laravel","php","eloquent","sanctum","api"]},
  {"id":"fw-005","title":"Gin/Echo Go Web Server","command":"/go-web","platform":"Framework","category":"Framework","type":"Backend","summary":"Build Go web services with Gin/Echo: routing, middleware, validation, Swagger","description":"Go web framework: Gin/Echo router setup, middleware chain (auth, CORS, logging, recovery), request binding/validation, Swagger with swaggo, and graceful shutdown","syntax":"/go-web [framework] [--middleware auth,cors,logging] [--swagger] [--graceful]","example":"/go-web gin --middleware jwt,cors,logger --swagger --graceful","tags":["go","gin","echo","golang","rest"]},
  {"id":"fw-006","title":"SvelteKit Full-Stack","command":"/sveltekit","platform":"Framework","category":"Framework","type":"Fullstack","summary":"Build SvelteKit apps: server routes, load functions, form actions, SSR/SSG","description":"SvelteKit mastery: +page.server.ts load functions, form actions for progressive enhancement, hooks.server.ts, adapter-node/vercel deployment, Prisma integration, and SvelteKit Auth","syntax":"/sveltekit [feature] [--ssr|ssg|spa] [--auth] [--db prisma]","example":"/sveltekit ecommerce --ssr --auth --db prisma","tags":["sveltekit","svelte","fullstack","ssr","typescript"]},
  {"id":"fw-007","title":"Astro Static Site Builder","command":"/astro-build","platform":"Framework","category":"Framework","type":"Frontend","summary":"Build Astro sites: islands architecture, content collections, view transitions","description":"Astro framework: zero-JS by default, Islands for interactive components, content collections with Zod schema, view transitions, MDX support, and adapter for Vercel/Netlify","syntax":"/astro-build [site-type] [--ui react|svelte|vue] [--content-collections] [--adapter vercel]","example":"/astro-build blog --ui react --content-collections --adapter vercel","tags":["astro","static-site","islands","performance","seo"]},
  {"id":"fw-008","title":"tRPC Type-Safe API","command":"/trpc","platform":"Framework","category":"Framework","type":"API","summary":"Build end-to-end type-safe APIs with tRPC: routers, procedures, subscriptions","description":"tRPC setup: router definitions, query/mutation procedures, input validation with Zod, subscriptions via WebSocket, context with auth, Next.js integration, and React Query adapter","syntax":"/trpc [router] [--procedures query,mutation,subscription] [--auth] [--nextjs]","example":"/trpc user --procedures query,mutation --auth --nextjs","tags":["trpc","typescript","type-safe","nextjs","react"]},
]

def main():
    print(f"Loading {DATA_FILE}...")
    with open(DATA_FILE, 'r') as f:
        existing = json.load(f)
    
    existing_ids = {s.get('id') for s in existing}
    existing_cmds = {s.get('command') for s in existing}
    
    added = 0
    skipped = 0
    for skill in NEW_SKILLS:
        if skill['id'] in existing_ids or skill['command'] in existing_cmds:
            skipped += 1
            continue
        existing.append(skill)
        existing_ids.add(skill['id'])
        existing_cmds.add(skill['command'])
        added += 1
    
    with open(DATA_FILE, 'w') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Added: {added} skills | Skipped (duplicate): {skipped}")
    print(f"📊 Total skills now: {len(existing)}")

if __name__ == '__main__':
    main()
