#!/usr/bin/env python3
"""
facebook_insights_to_skills.py
Analyse les insights Facebook → génère de nouveaux skills pour KortexDeck
"""
import json, os

# Skills générés à partir de l'analyse Facebook anticipée
# (sera enrichi avec les résultats réels du browser agent)
FACEBOOK_INSIGHTS_SKILLS = [
  # ===== MARKETING DIGITAL & SOCIAL MEDIA =====
  {"id":"mkt-001","title":"Facebook Ads Campaign Builder","command":"/fb-ads","platform":"Marketing","category":"Marketing & Social","type":"Advertising","summary":"Build Facebook/Meta ad campaigns: objectives, audiences, creatives, bidding","description":"Create complete Facebook ad campaigns: campaign objectives (conversions, traffic, awareness), custom audiences, lookalike audiences, detailed targeting, A/B split testing, creative variations (image/video/carousel/stories), pixel integration, ROAS optimization, and budget allocation (CBO/ABO)","syntax":"/fb-ads [objective] [--audience custom|lookalike] [--creative carousel|video|story] [--budget]","example":"/fb-ads conversions --audience lookalike --creative video --budget 100/day","tags":["facebook-ads","meta-ads","marketing","advertising","social-media"]},
  {"id":"mkt-002","title":"Meta Pixel & Conversion API","command":"/meta-pixel","platform":"Marketing","category":"Marketing & Social","type":"Analytics","summary":"Implement Meta Pixel + Conversions API for accurate event tracking","description":"Set up server-side + browser-side event tracking: Meta Pixel installation, Conversions API (CAPI) for iOS 14+ privacy, event deduplication, custom events, standard events (Purchase, Lead, AddToCart), and Facebook Analytics dashboard","syntax":"/meta-pixel [events] [--server-side] [--dedup] [--test-events]","example":"/meta-pixel purchase,lead,add-to-cart --server-side --dedup --test-events","tags":["meta-pixel","capi","tracking","facebook","analytics"]},
  {"id":"mkt-003","title":"Social Media Content Calendar","command":"/content-calendar","platform":"Marketing","category":"Marketing & Social","type":"Strategy","summary":"Build automated content calendar: posting schedule, content mix, platform strategy","description":"Create content strategy: 80/20 rule (value vs promotion), posting frequency by platform (FB 1-2x/day, IG 1x/day), content pillars, hashtag research, competitor analysis, user-generated content strategy, and Buffer/Hootsuite automation","syntax":"/content-calendar [platforms] [--frequency] [--content-mix educational:50,entertainment:30,promotional:20]","example":"/content-calendar facebook,instagram,linkedin --frequency 2x/day --content-mix educational:50,entertainment:30,promotional:20","tags":["content-calendar","social-media","marketing","buffer","hootsuite"]},
  {"id":"mkt-004","title":"Facebook Group Growth Hacker","command":"/fb-group","platform":"Marketing","category":"Marketing & Social","type":"Community","summary":"Grow and engage Facebook groups: automated welcome, engagement triggers, content strategy","description":"Facebook Group management: automated welcome messages, engagement pods, content recycling strategy, membership questions screening, pinned posts, milestones engagement, cross-promotion, and group-to-funnel conversion","syntax":"/fb-group [group-type] [--automate welcome,posts] [--monetize] [--funnel]","example":"/fb-group community --automate welcome,posts --monetize --funnel email-list","tags":["facebook-groups","community","marketing","engagement","funnel"]},
  {"id":"mkt-005","title":"Video Marketing Producer","command":"/video-marketing","platform":"Marketing","category":"Marketing & Social","type":"Video","summary":"Create viral-ready video content: hooks, captions, thumbnails, optimization","description":"Video marketing system: 3-second hook optimization, pattern interrupt techniques, captions for silent viewing, B-roll strategy, thumbnail split testing, optimal lengths per platform (Reels 15-30s, YouTube Shorts 60s, TikTok 21-34s), and repurposing workflow","syntax":"/video-marketing [platform] [--duration] [--hook-style curiosity|shock|story] [--captions]","example":"/video-marketing reels --duration 30s --hook-style curiosity --captions","tags":["video-marketing","reels","tiktok","youtube-shorts","viral"]},
  {"id":"mkt-006","title":"Landing Page Converter","command":"/landing-page","platform":"Marketing","category":"Marketing & Social","type":"CRO","summary":"Build high-converting landing pages: above-fold, social proof, CTA optimization","description":"CRO-optimized landing page: above-the-fold headline formula (Problem + Solution + Benefit), social proof (testimonials, logos, numbers), urgency/scarcity triggers, multiple CTAs, mobile-first design, page speed optimization, and Hotjar heatmap integration","syntax":"/landing-page [offer] [--cro] [--social-proof] [--urgency] [--ab-test]","example":"/landing-page lead-magnet --cro --social-proof --urgency countdown --ab-test","tags":["landing-page","cro","conversion","a-b-testing","marketing"]},
  {"id":"mkt-007","title":"Email Marketing Automation","command":"/email-automation","platform":"Marketing","category":"Marketing & Social","type":"Email","summary":"Build email sequences: welcome series, nurture campaigns, cart abandonment","description":"Email automation flows: welcome series (5-7 emails), nurture sequence, cart abandonment (3-email flow), re-engagement campaigns, segmentation by behavior/tags, subject line optimization (7 formulas), personalization tokens, and Klaviyo/Mailchimp/ActiveCampaign setup","syntax":"/email-automation [sequence-type] [--provider klaviyo|mailchimp|activecampaign] [--emails 7] [--segment]","example":"/email-automation welcome-series --provider klaviyo --emails 7 --segment by-behavior","tags":["email-marketing","automation","klaviyo","mailchimp","sequences"]},
  {"id":"mkt-008","title":"AI Copywriter Pro","command":"/ai-copy","platform":"Marketing","category":"Marketing & Social","type":"Copywriting","summary":"Generate persuasive copy: headlines, ad copy, product descriptions, CTAs","description":"AI-powered copywriting: AIDA formula (Attention, Interest, Desire, Action), PAS formula (Problem, Agitate, Solution), benefit-driven headlines, power words psychology, social proof integration, urgency triggers, and platform-specific character limits","syntax":"/ai-copy [format] [--formula aida|pas|4p] [--tone professional|casual|urgent] [--platform fb|google|email]","example":"/ai-copy facebook-ad --formula pas --tone urgent --platform fb","tags":["copywriting","ai","marketing","aida","pas","headlines"]},

  # ===== BUSINESS & ENTREPRENEURSHIP =====
  {"id":"biz-001","title":"SaaS Funnel Architect","command":"/saas-funnel","platform":"Business","category":"Business & Startup","type":"Strategy","summary":"Design SaaS funnel: awareness, trial, activation, retention, expansion","description":"SaaS growth funnel: AARRR metrics (Acquisition, Activation, Retention, Referral, Revenue), product-led growth (PLG) strategy, free trial optimization, onboarding flow, in-app triggers, churn reduction, NPS tracking, and LTV/CAC optimization","syntax":"/saas-funnel [stage] [--model plg|sales-led] [--metrics aarrr] [--optimize ltv-cac]","example":"/saas-funnel activation --model plg --metrics aarrr --optimize ltv-cac","tags":["saas","funnel","plg","growth","startup"]},
  {"id":"biz-002","title":"E-commerce Product Lister","command":"/ecom-product","platform":"Business","category":"Business & Startup","type":"E-commerce","summary":"Optimize product listings: SEO titles, bullet points, descriptions, images","description":"Amazon/Shopify product optimization: keyword-rich titles (brand + model + key features), 5 benefit-focused bullet points, A+ content, backend keywords, review generation strategy, image sequencing (hero + lifestyle + infographic + dimension), and PPC integration","syntax":"/ecom-product [platform] [--keywords] [--seo] [--a-plus-content] [--review-strategy]","example":"/ecom-product amazon --keywords 15 --seo --a-plus-content --review-strategy","tags":["ecommerce","amazon","shopify","product-listing","seo"]},
  {"id":"biz-003","title":"Freelance Proposal Writer","command":"/freelance-proposal","platform":"Business","category":"Business & Startup","type":"Sales","summary":"Write winning freelance proposals: problem diagnosis, solution, pricing, trust signals","description":"Freelance proposal framework: client pain point identification, custom solution presentation, portfolio proof selection, pricing psychology (3 tiers), timeline milestones, risk reversal (guarantee), social proof (testimonials), and follow-up sequence","syntax":"/freelance-proposal [service] [--client-type] [--pricing tiered] [--guarantee]","example":"/freelance-proposal web-development --client-type startup --pricing tiered --guarantee","tags":["freelance","proposal","sales","copywriting","upwork"]},
  {"id":"biz-004","title":"Business Plan Generator","command":"/business-plan","platform":"Business","category":"Business & Startup","type":"Strategy","summary":"Generate complete business plan: executive summary, market analysis, financial projections","description":"Business plan components: executive summary (1-pager), market size (TAM/SAM/SOM), competitive analysis (Porter's 5 Forces), business model canvas, go-to-market strategy, financial projections (3-year P&L), and investor pitch deck outline","syntax":"/business-plan [type] [--market-analysis] [--financials 3-year] [--pitch-deck]","example":"/business-plan saas-startup --market-analysis --financials 3-year --pitch-deck","tags":["business-plan","startup","investors","financial-projections","strategy"]},

  # ===== IA & AUTOMATION =====
  {"id":"ia-001","title":"ChatGPT Prompt Engineer Pro","command":"/chatgpt-prompt","platform":"AI","category":"AI & Automation","type":"Prompting","summary":"Engineer advanced ChatGPT prompts: chain-of-thought, few-shot, role prompting, structured output","description":"Advanced prompt engineering: chain-of-thought (step-by-step reasoning), few-shot examples, role + context + task + format structure, self-consistency sampling, tree-of-thought, prompt chaining, and output format enforcement (JSON, tables, lists)","syntax":"/chatgpt-prompt [task] [--technique cot|few-shot|role|tot] [--output json|table|markdown]","example":"/chatgpt-prompt data-analysis --technique cot,few-shot --output json","tags":["chatgpt","prompt-engineering","few-shot","chain-of-thought","openai"]},
  {"id":"ia-002","title":"n8n Workflow Automator","command":"/n8n-workflow","platform":"AI","category":"AI & Automation","type":"No-Code","summary":"Build n8n automation workflows: triggers, HTTP requests, AI nodes, data transforms","description":"n8n workflow design: webhook triggers, HTTP request nodes, OpenAI/Gemini AI integration, Google Sheets sync, Airtable automation, Telegram/Discord notifications, data transformation (JS code nodes), error handling, and schedule triggers","syntax":"/n8n-workflow [trigger] [--nodes http,ai,sheets] [--notify telegram|discord] [--schedule]","example":"/n8n-workflow webhook --nodes http,openai,sheets --notify telegram --schedule daily","tags":["n8n","automation","no-code","workflow","zapier"]},
  {"id":"ia-003","title":"Make.com Scenario Builder","command":"/make-scenario","platform":"AI","category":"AI & Automation","type":"No-Code","summary":"Build Make.com (Integromat) scenarios for business automation","description":"Make.com automation: multi-module scenarios, data mapping, iterators, aggregators, filters with conditions, error handlers, Google Workspace integration, CRM sync (HubSpot/Salesforce), and webhook processing","syntax":"/make-scenario [apps] [--trigger webhook|schedule] [--modules] [--error-handling]","example":"/make-scenario google-sheets,openai,slack --trigger webhook --error-handling","tags":["make","integromat","automation","no-code","google-workspace"]},
  {"id":"ia-004","title":"Chatbot Builder","command":"/chatbot","platform":"AI","category":"AI & Automation","type":"AI","summary":"Build customer service chatbots: intent recognition, flow design, multi-platform deployment","description":"Chatbot development: conversation flow design, intent classification, entity extraction, fallback handling, escalation to human, multi-platform (WhatsApp, Facebook Messenger, Telegram, website widget), FAQ training, and analytics dashboard","syntax":"/chatbot [platform] [--nlp gpt4|dialogflow|rasa] [--channels whatsapp,messenger,telegram] [--analytics]","example":"/chatbot customer-service --nlp gpt4 --channels whatsapp,messenger --analytics","tags":["chatbot","nlp","whatsapp","messenger","automation","ai"]},
  {"id":"ia-005","title":"AI Agent Pipeline Designer","command":"/agent-pipeline","platform":"AI","category":"AI & Automation","type":"Agents","summary":"Design multi-agent pipelines: orchestration, tool use, memory, human-in-the-loop","description":"Multi-agent system design: agent roles (researcher, writer, coder, critic), orchestration patterns (sequential, parallel, hierarchical), tool integration (web search, code execution, file ops), shared memory (vector store), human approval gates, and observability","syntax":"/agent-pipeline [task] [--agents researcher,writer,critic] [--memory vectorstore] [--orchestration sequential|parallel]","example":"/agent-pipeline content-creation --agents researcher,writer,critic --memory vectorstore --orchestration parallel","tags":["ai-agents","langchain","autogen","crewai","multi-agent","orchestration"]},
  {"id":"ia-006","title":"WhatsApp Business Bot","command":"/whatsapp-bot","platform":"AI","category":"AI & Automation","type":"Messaging","summary":"Build WhatsApp Business API bot: catalog, orders, customer support, broadcasts","description":"WhatsApp Business automation: Meta Cloud API integration, message templates (text, image, document, interactive), button/list messages, product catalog integration, order management, broadcast lists, and webhook processing","syntax":"/whatsapp-bot [use-case] [--api meta-cloud|twilio|360dialog] [--catalog] [--broadcast]","example":"/whatsapp-bot customer-support --api meta-cloud --catalog --broadcast","tags":["whatsapp","business-api","chatbot","messaging","automation"]},

  # ===== FREELANCE & FORMATION =====
  {"id":"fr-001","title":"Cours en ligne Creator","command":"/online-course","platform":"Education","category":"Formation & Education","type":"Content","summary":"Créer et monétiser un cours en ligne: structure, vidéos, plateforme, marketing","description":"Création de cours: définition du persona apprenant, curriculum design (modules + leçons), script de vidéo engagant, production (OBS + Descript), plateforme (Teachable/Kajabi/Podia), pricing (one-time vs subscription), lancement (email list + webinar)","syntax":"/online-course [topic] [--platform teachable|kajabi|podia] [--format video|hybrid] [--pricing]","example":"/online-course facebook-ads --platform teachable --format video --pricing one-time 497","tags":["online-course","teachable","kajabi","education","monetization"]},
  {"id":"fr-002","title":"Community Manager Toolkit","command":"/community-manager","platform":"Marketing","category":"Formation & Education","type":"Community","summary":"Gérer une communauté en ligne: engagement, modération, croissance, monétisation","description":"Community management: posting schedule (3-5x/week), engagement framework (questions, polls, challenges), member spotlight strategy, event creation (live Q&A, workshops), moderator guidelines, growth strategies (referral programs), and monetization (membership tiers)","syntax":"/community-manager [platform] [--size] [--engagement-rate target] [--monetize]","example":"/community-manager facebook-group --size 10k --engagement-rate 15% --monetize membership","tags":["community-manager","facebook-groups","engagement","moderation","growth"]},

  # ===== WEB3 & TECH AVANCÉ =====
  {"id":"w3-001","title":"Solidity Smart Contract","command":"/solidity","platform":"Web3","category":"Blockchain & Web3","type":"Smart Contract","summary":"Write Solidity smart contracts: ERC-20, ERC-721, DeFi protocols, security","description":"Solidity development: ERC-20 token standard, ERC-721/1155 NFT contracts, OpenZeppelin libraries, reentrancy guards, access control (Ownable, RBAC), Hardhat/Foundry testing, gas optimization, and Slither security audit","syntax":"/solidity [contract-type] [--standard erc20|erc721|erc1155] [--oz] [--audit] [--test hardhat|foundry]","example":"/solidity nft-collection --standard erc721 --oz --audit slither --test hardhat","tags":["solidity","ethereum","smart-contract","nft","defi","web3"]},

  # ===== DESIGN & CRÉATIF =====
  {"id":"des-001","title":"Figma Design System","command":"/figma-system","platform":"Design","category":"Design & Créatif","type":"UI/UX","summary":"Build Figma design system: components, styles, variables, auto-layout","description":"Figma design system: atomic design (atoms → organisms), component variants, design tokens (colors, typography, spacing), auto-layout responsive components, prototyping flows, developer handoff (Inspect panel), and Figma Variables for theming","syntax":"/figma-system [brand] [--components] [--tokens] [--dark-mode] [--prototype]","example":"/figma-system saas-app --components button,input,card,modal --tokens --dark-mode --prototype","tags":["figma","design-system","ui-ux","components","design-tokens"]},
  {"id":"des-002","title":"Canva Pro Template Creator","command":"/canva-template","platform":"Design","category":"Design & Créatif","type":"Graphic Design","summary":"Create professional Canva templates: posts, stories, presentations, thumbnails","description":"Canva template design: brand kit setup (colors, fonts, logo), social media post templates (feed, story, reel cover), presentation decks, YouTube thumbnails, podcast covers, and Canva Pro batch resizing for all platforms","syntax":"/canva-template [format] [--brand-kit] [--platforms fb,ig,linkedin,youtube] [--size all]","example":"/canva-template social-pack --brand-kit --platforms fb,ig,linkedin --size all","tags":["canva","graphic-design","social-media","templates","branding"]},
]

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_file = os.path.join(base_dir, '../src/data/commandsData.json')
    
    with open(data_file) as f:
        existing = json.load(f)
    
    existing_ids = {s.get('id') for s in existing}
    existing_cmds = {s.get('command') for s in existing}
    
    added = 0
    for skill in FACEBOOK_INSIGHTS_SKILLS:
        if skill['id'] in existing_ids or skill['command'] in existing_cmds:
            continue
        existing.append(skill)
        existing_ids.add(skill['id'])
        existing_cmds.add(skill['command'])
        added += 1
    
    with open(data_file, 'w') as f:
        json.dump(existing, f, indent=2, ensure_ascii=False)
    
    print(f"✅ Added {added} skills from Facebook insights")
    print(f"📊 Total: {len(existing)} skills")
    
    # Show new categories
    cats = {}
    for s in existing:
        c = s.get('category', 'Unknown')
        cats[c] = cats.get(c, 0) + 1
    new_cats = ['Marketing & Social', 'Business & Startup', 'AI & Automation', 'Formation & Education', 'Blockchain & Web3', 'Design & Créatif']
    for cat in new_cats:
        if cat in cats:
            print(f"  {cat}: {cats[cat]} skills")

if __name__ == '__main__':
    main()
