#!/usr/bin/env python3
"""Regenerate public/api/skills.json, SKILL.md catalog, and ZIP"""
import json, os, zipfile, shutil

BASE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(BASE, '..')
DATA_FILE = os.path.join(ROOT, 'src/data/commandsData.json')
API_FILE = os.path.join(ROOT, 'public/api/skills.json')
CATALOG_DIR = '/Users/ilan/.gemini/antigravity/scratch/skills_catalog'
ZIP_DEST = os.path.join(ROOT, 'public/kortexdeck_500_skills.zip')

def slugify(text):
    slug = ''.join(c if c.isalnum() or c in '-_' else '-' for c in text.lower()).strip('-')
    return slug[:60]

def make_skill_md(skill):
    title = skill.get('title', '')
    command = skill.get('command', '')
    platform = skill.get('platform', '')
    category = skill.get('category', '')
    skill_type = skill.get('type', '')
    summary = skill.get('summary', '')
    description = skill.get('description') or summary
    syntax = skill.get('syntax') or command
    example = skill.get('example', '')
    tags = skill.get('tags', [])
    
    tags_lines = '\n'.join('- ' + t for t in tags) if tags else '- general'
    example_block = ('```\n' + example + '\n```') if example else '_No example provided_'
    
    return f"""---
name: {title}
command: {command}
platform: {platform}
category: {category}
type: {skill_type}
source: kortexdeck
---

# {title}

## Description

{description}

## When to Use

{summary}

## Command

```
{syntax}
```

## Example

{example_block}

## Tags

{tags_lines}

---
*Generated by KortexDeck v2.5 — https://cohenwebstudio.com/kortexdeck*
"""

def main():
    with open(DATA_FILE) as f:
        data = json.load(f)
    
    # 1. Update API
    os.makedirs(os.path.join(ROOT, 'public/api'), exist_ok=True)
    with open(API_FILE, 'w') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f'✅ API updated: {len(data)} skills at public/api/skills.json')
    
    # 2. Regenerate SKILL.md catalog (only new)
    os.makedirs(CATALOG_DIR, exist_ok=True)
    existing = set(os.listdir(CATALOG_DIR))
    added = 0
    for skill in data:
        name = skill.get('title') or skill.get('command') or skill.get('id', 'skill')
        slug = slugify(name)
        if not slug:
            continue
        dir_path = os.path.join(CATALOG_DIR, slug)
        if os.path.isdir(dir_path):
            continue
        os.makedirs(dir_path, exist_ok=True)
        with open(os.path.join(dir_path, 'SKILL.md'), 'w') as f:
            f.write(make_skill_md(skill))
        added += 1
    
    total = len([d for d in os.listdir(CATALOG_DIR) if os.path.isdir(os.path.join(CATALOG_DIR, d))])
    print(f'✅ SKILL.md catalog: +{added} new | {total} total dirs')
    
    # 3. Regenerate ZIP
    zip_path = os.path.join(CATALOG_DIR, 'kortexdeck_skills.zip')
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(CATALOG_DIR):
            dirs[:] = [d for d in dirs if d not in ('__pycache__',)]
            for file in files:
                if file == 'SKILL.md':
                    fp = os.path.join(root, file)
                    arcname = os.path.relpath(fp, CATALOG_DIR)
                    zf.write(fp, arcname)
    
    zip_size = os.path.getsize(zip_path) // 1024
    print(f'✅ ZIP: {zip_size} KB at {zip_path}')
    
    shutil.copy(zip_path, ZIP_DEST)
    print(f'✅ ZIP copied to public/')

if __name__ == '__main__':
    main()
