#!/usr/bin/env bash
# ==============================================================================
# KORTEXDECK - LOCAL SYNC AUTOMATION PLUGIN
# Cohen Web Studio (https://cohenwebstudio.com/kortexdeck)
#
# Synchronizes selected command & skill stack to:
#   1. ~/.cursorrules (for Cursor IDE)
#   2. ~/.claude/CLAUDE.md (for Claude Code & Claude Desktop)
# ==============================================================================

set -e

CYAN='\033[0;36m'
AMBER='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     KORTEXDECK - Neural Stack Synchronizer (v2.5)          ║${NC}"
echo -e "${CYAN}║     by Cohen Web Studio (https://cohenwebstudio.com)       ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"

HOME_DIR="${HOME:-/Users/$USER}"
CURSOR_DEST="$HOME_DIR/.cursorrules"
CLAUDE_DIR="$HOME_DIR/.claude"
CLAUDE_DEST="$CLAUDE_DIR/CLAUDE.md"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

echo -e "\n${AMBER}[1/4] Verifying destination directories...${NC}"
mkdir -p "$CLAUDE_DIR"
echo -e "  ✓ Claude directory: $CLAUDE_DIR"

# Backup existing files if present
echo -e "\n${AMBER}[2/4] Generating safety backups...${NC}"
if [ -f "$CURSOR_DEST" ]; then
    cp "$CURSOR_DEST" "${CURSOR_DEST}.bak_${TIMESTAMP}"
    echo -e "  ✓ Safety backup created: ${CURSOR_DEST}.bak_${TIMESTAMP}"
else
    echo -e "  ℹ No existing .cursorrules found (creating new)."
fi

if [ -f "$CLAUDE_DEST" ]; then
    cp "$CLAUDE_DEST" "${CLAUDE_DEST}.bak_${TIMESTAMP}"
    echo -e "  ✓ Safety backup created: ${CLAUDE_DEST}.bak_${TIMESTAMP}"
else
    echo -e "  ℹ No existing CLAUDE.md found (creating new)."
fi

# Retrieve stack content
DATA_SOURCE="${1:-}"

if [ -n "$DATA_SOURCE" ] && [ -f "$DATA_SOURCE" ]; then
    echo -e "\n${AMBER}[3/4] Reading custom stack from $DATA_SOURCE...${NC}"
else
    echo -e "\n${AMBER}[3/4] Generating active engineering stack...${NC}"
fi

# Write ~/.cursorrules
cat << 'EOF' > "$CURSOR_DEST"
# ==============================================================================
# .cursorrules - KortexDeck Configuration
# Generated by KortexDeck (Cohen Web Studio)
# ==============================================================================

# GENERAL EXECUTION INVARIANTS
- Prioritize modular architecture, strict TypeScript typing (zero 'any'), and robust error handling.
- Verify OWASP security standards (no plaintext secrets, Zod runtime validation, PostgreSQL RLS).
- For each refactor or feature, ensure regression tests pass prior to finalizing.

# INTEGRATED DIRECTIVES & SHORTCUTS
- @codebase : Explore dependency graph before making architectural changes.
- @definitions : Inspect strict types and function signatures.
- /goal : Deconstruct complex objectives into iterative verified steps.
- /review : Perform self-critique of git diff before submission.
EOF

# Write ~/.claude/CLAUDE.md
cat << 'EOF' > "$CLAUDE_DEST"
# CLAUDE.md - Global Project Configuration
# Generated via KortexDeck (https://cohenwebstudio.com/kortexdeck)

## Standards & Execution Guidelines
- **Environment**: Claude Code CLI & Claude Desktop
- **Engineering Philosophy**: Modular, clean, type-safe code with zero regressions.
- **Security**: Guard API keys and sensitive tokens in environment variables (.env).
- **Recommended Workflow**:
  1. `/compact` : Optimize context window regularly.
  2. `/review` : Methodical review of git diff and test coverage.
  3. `/test` : Run test suites to verify system stability.
EOF

echo -e "\n${GREEN}[4/4] Synchronization completed successfully!${NC}"
echo -e "  ✨ Updated: ~/.cursorrules (${CURSOR_DEST})"
echo -e "  ✨ Updated: ~/.claude/CLAUDE.md (${CLAUDE_DEST})"
echo -e "\n${CYAN}Your Cursor IDE and Claude Code environments are now synchronized.${NC}\n"
